### ISSUE TITLE
Turn off mouseover text on nav and images

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#1]
Description is shown on mouseover on nav items - hold your mouse over the Contact button to see. Turn this off.

Title is shown on mouseover on images - hold your mouse over the image at http://beta.jazkarta.com/about to see. Turn this off.

**Comment by cguardia** [comment]
Only way to turn it off is to remove title attribute from tags. Done.

**Comment by skleinfeldt** [comment]
Thanks @cguardia - was that the miracle of a diazo rule? Works like a charm although I guess it is degrading the site accessibility...
