### ISSUE TITLE
Footer tweaks

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#101]
Could we have more space between Get In Touch and What We Do? Note that on Leah's design there is a large space here (not 3 evenly spaced columns).

**Comment by alecpm** [comment]
This should be fixed.

**Comment by skleinfeldt** [comment]
@alecpm the footer looks wonky to me on FF and Safari - the last column is wrapping underneath the first one. Look at any page. I shift-reloaded. Something went wrong in the deployment?

**Comment by alecpm** [comment]
This should be fixed now.

**Comment by alecpm** [comment]
Nevermind, fix didn't get deployed.  Will be fixed in five minutes.

**Comment by skleinfeldt** [comment]
Yay!
