### ISSUE TITLE
Need advice and maybe a fix for small tile containing photo

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#103]
See http://beta.jazkarta.com/services/training. The image is a rich text tile with the CSS class for "Vertically centered text tile". I used the "preview" scale in the HTML for the <a> tag for the image, and created a crop for it. 

```<p><img class="image-inline" src="resolveuid/d53ceeda74ac4e7eb1a2133951e3ac79/@@images/image/preview" alt="" data-linktype="image" data-scale="preview" data-val="d53ceeda74ac4e7eb1a2133951e3ac79" /></p>```

This is the scale that is supposed to match the tiles but it may not match any more, because the image isn't the right size.

It would be easier to use a basic tile for this and drop the image on it as content - although I don't want mouseover behavior or a link. I tried using a basic tile and found that I could get rid of the title by removing that text and removing the mouseover by selecting "Vertically centered text tile". Visually it looks perfect, however I couldn't see how to get rid of the link to the image.

Should I be doing this another way? or does CSS for the small rich text tile with an image need adjustment?

Assigning to @alecpm because this probably needs a CSS fix.

**Comment by alecpm** [comment]
The p tag styling for those boxes includes padding to ensure the text doesn't run to the edge of the box.  That's not desirable for an image though, so it's best to replace the p tag with a div tag.  Looks OK now.

**Comment by skleinfeldt** [comment]
AHA! Thank you!
