### ISSUE TITLE
Adjust CSS used for "Image mouseover basic tile"

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#104]
Use H2 (I assume) style that is used for "Text mouseover basic tile", not H1 all caps. (I'm sure you chose the latter because it is a Title field that is shown, not Description. However we will be using both styles on the same page so the mouseover text should be consistent.)

**Comment by cguardia** [comment]
They are H2. H3 looks too small. Maybe add a class that turns off the all caps here?

**Comment by skleinfeldt** [comment]
Hmmm, in that case how about using the class that @alecpm created/used for "Text mouseover basic tile"?

**Comment by cguardia** [comment]
I just removed the uppercase transform from the css for mouseover tiles. Not deployed yet.

**Comment by cguardia** [comment]
This is now deployed.

**Comment by skleinfeldt** [comment]
Looks good!
