### ISSUE TITLE
Switch to t2.large

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#108]
Alec says "check if using a t2.large helps with some of the performance issues we're seeing (which seem to be on the network or I/O side)."

Please make the switch asap so we can decide next week what type of reserved instance to purchase.

**Comment by skleinfeldt** [comment]
@alecpm nudge?

**Comment by skleinfeldt** [comment]
@alecpm nudge nudge?

**Comment by alecpm** [comment]
I think this is no longer necessary.  t2.large will give us more RAM, but I don't think that will buy us much performance.  The changes to the tmp storage, combined with some re-initializing the EBS volumes appears to have led to some significant improvements.  Let me know if you are still seeing performance issues though.

**Comment by skleinfeldt** [comment]
Closing this - I've done some informal testing as anonymous and performance seems fine.
