### ISSUE TITLE
Error viewing Project when logged in

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#113]
error while rendering plone.belowcontenttitle.documentbyline 

You can see this on https://jazkarta.com/projects/uc-davis-opsworks-deployment-and-plone-consulting but you must be logged in.

**Comment by skleinfeldt** [comment]
Corrected the above, the problem is not related to published state, but to being logged in.

**Comment by cguardia** [comment]
I don't get an error, logged in or not.

**Comment by skleinfeldt** [comment]
To clarify, the page displays, but it shows the error msg I pasted in where
the byline would be.

On Monday, February 29, 2016, Carlos de la Guardia <notifications@github.com>
wrote:

> I don't get an error, logged in or not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jazkarta/jazkarta.com/issues/113#issuecomment-190437873>
> .
>


-- 
Sally Kleinfeldt - sally@jazkarta.com
Open Source Technology Solutions

http://jazkarta.com

**Comment by cguardia** [comment]
This problem was related to the unfinished migration, which errored out when tried from the migration page in Plone. After a bit of trying to figure it out, I decided to run the upgrade steps one by one from portal_setup. They all worked! 

Mystery not explained, but problem solved.
