### ISSUE TITLE
Embedded Slideshare presentations not showing

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#114]
From Witek: In the news section, the embedded slideshare presentations are not showing up in the posts eg: https://jazkarta.com/news/leading-with-lead-images

After more investigating it turned out to be my browsers are blocking them due to
"This page is trying to load scripts from unauthenticated sources"
https://support.google.com/chrome/answer/1342714

Witek didn't say which browser, but it happens to me on Firefox.

**Comment by skleinfeldt** [comment]
@cguardia could you take a look at this please?

**Comment by cguardia** [comment]
The switch to https-only caused previous embed links to do this. Fixed all, but this one doesn't seem to be valid on slideshare anymore:

https://jazkarta.com/news/plone-for-education-bibliographies-take-2

**Comment by skleinfeldt** [comment]
Yes, that's a known problem. I unpublished it because I used a copyrighted image on the cover and got caught, had to pay a fine!

Thanks much @cguardia and @witek for the catch.
