### ISSUE TITLE
Traceback on Mountaineers project image

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#115]
I just tried to edit the Mountaineers "project" (adding a name to the design credit field) and it's resulted in a traceback: https://jazkarta.com/projects/the-mountaineers-website (view and also @@croppingeditor)

Is there any chance this is related to that hard to track down bug with the images losing their crops? (since the traceback has to do with image scaling.)

**Comment by cguardia** [comment]
This  is working now. Hopefully there will be no more errors like this, since we switched to plone.scale master. We'll probably need to keep an eye on the release to remove the checkout when it's no longer needed.

**Comment by skleinfeldt** [comment]
I made ticket #121 for this.
