### ISSUE TITLE
Fix collective.isotope JS dependency on data grid field

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#117]
The isotope control panel relies on data grid field, but because data grid field is part of the Plone legacy bundle, it is loaded too late. So have the isotope bundle depend on data grid field so it is loaded in the right order.

**Comment by skleinfeldt** [comment]
FYI filed from the plone.org sprint. Concern was expressed that data grid field might be getting old and funky....

**Comment by skleinfeldt** [comment]
@alecpm did this happen?

**Comment by alecpm** [comment]
I've upgraded the datagridfield to the latest version though it still uses the legacy bundle. The package appears to be well maintained though. The control panel seems to be working correctly now. Closing.
