### ISSUE TITLE
Fix collective.isotope to display SVG images

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#118]
In https://github.com/collective/collective.isotope/blob/master/src/collective/isotope/browser/templates/isotope.pt

It uses this code to display the item's image:

```
<img tal:define="scales obj/@@images;
         scale python:scales.scale('image', 'thumb')"
```

This will not display an SVG image, and it is going to be a heavy lift to fix the Plone image scaling to handle SVGs. In the interim, can this code be changed to detect whether the image is an SVG, and if it is, display it with @alecpm 's special SVG display workaround code.

```
tal:attributes="src string:${badge/absolute_url}/@@images/image;
                                  alt badge/Title"/>
```

**Comment by skleinfeldt** [comment]
@alecpm did this get done? It's working on https://plone.org/community/badges

**Comment by alecpm** [comment]
Yes, this was fixed so that the SVG is rendered directly rather than trying to use a scaled thumbnail or similar when the image is an SVG.
