### ISSUE TITLE
Reduce AWS bill

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#119]
Suggestions from @alecpm 

- [x] remove t1.micro instance called ansible-ec2 running in us-west-2 since March 23, 2016 (@cguardia created for GHD.)
- [x] in us-east-1 there are two un-assigned elastic IPs (unassigned but reserved IPs have an hourly charge) 54.83.8.221 and 54.83.8.221. It's unlikely we need these, but it might be wise to check before deleting them.
- [x] there are two EBS volumes (8 GB magnetic and 200 GB SSD) attached to stopped instances "JTesting" and "Nudow" in us-east-1, these instances/volumes were created in 2013 and 2014 and appear not to have been running for some time. remove?
- [x] it might make sense to move the oldjazcom S3 bucket with the old site backup into Glacier storage to save a few bucks a month.
- [x] check what impact SES, S3 and Route53 costs have (Alec suspects those are all quite small.)

**Comment by cguardia** [comment]
@alecpm what's involved in moving to Glacier. Do I need to get the s3 data to my fs and tar it to move it there? Is there a way to move the contents of an s3 bucket to Glacier directly?

**Comment by alecpm** [comment]
For an individual item you can go to Properties -> Details  and set Storage Class to "Standard - Infrequent Access" which won't put them in Glacier, but will put them in a lower cost storage. You can also setup a lifecycle rule for the bucket that automatically moves objects into glacier after some amount of inactivity: http://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html

**Comment by cguardia** [comment]
Moved everything in oldjazcom to infrequent access storage.

**Comment by skleinfeldt** [comment]
Excellent. We'll see what the next bill says.

**Comment by skleinfeldt** [comment]
It went from $48 to $21, less than half. Yay!
