### ISSUE TITLE
Googlebot mobile fail

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#122]
Fix this: https://www.google.ca/webmasters/tools/mobile-friendly/?url=https%3A%2F%2Fjazkarta.com%2F

(I swear it looked OK when I checked a while ago, but something is messed up now.)

**Comment by davisagli** [comment]
It says "This page uses 6 resources which are blocked by robots.txt." and from the screenshot it looks like it is not loading the CSS. 

Why do we have this in robots.txt?
Disallow: /*?

**Comment by skleinfeldt** [comment]
According to the Site control panel:

`Sitemap: {portal_url}/sitemap.xml.gz

# Define access-restrictions for robots/spiders
# http://www.robotstxt.org/wc/norobots.html
`

Control panel also says "Warning The site configuration is outdated and needs to be upgraded." Add-ons says no upgrades needed.

**Comment by davisagli** [comment]
Fixed.

It took me an embarrassingly long time to realize that you can now edit robots.txt in the site control panel.

**Comment by skleinfeldt** [comment]
:-)

Thank you so much @davisagli

@alecpm you can probably apply the same fix to ploneconf.org.
