### ISSUE TITLE
Top nav partially covers sax image and text

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#123]
On iPhone 6

**Comment by alecpm** [comment]
I think this is fixed, though based on the description I'm not sure we were seeing the same thing. The sax image is extremely short on mobile screens, so short that it was smaller than the line browser default line-height for the container, leaving some random looking padding around it.

**Comment by skleinfeldt** [comment]
It looks a lot better. The first line "Agile Process" is partly cut off, presumably because the image is so short on mobile that there is no room for it. Would it be possible/easy to switch to a smaller font size for the overlay on mobile?

**Comment by alecpm** [comment]
Is it looking better for you now? I made a margin adjustment.

**Comment by skleinfeldt** [comment]
Yes, better. Top of "Agile Process" still goes off the image though.

**Comment by alecpm** [comment]
Can you send a screenshot. I'm not seeing that on my phone or in responsive mode on the browser, so it's hard for me to tune the CSS to account for it.

**Comment by skleinfeldt** [comment]
Sent.

**Comment by skleinfeldt** [comment]
OTOH it looks perfectly find on Doug's larger Android phone (and presumably your larger iPhone), and since most people have larger phones these days I'm going to drop this. It's very close on my small phone. Closing.
