### ISSUE TITLE
Can't see folder contents for custom types

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#128]
I just get a spinning wheel here:
- https://jazkarta.com/projects/folder_contents
- https://jazkarta.com/about/team/folder_contents

But not on /news or /services where there are OOTB object types

I can edit and view those object types OK.

This is blocking me from seeing my unpublished projects, renaming, etc. Assigned to @cguardia for the week of 2/6 - please help!

**Comment by skleinfeldt** [comment]
Note to self: when fixed, rename Pleiades id/shortname.

**Comment by cguardia** [comment]
Fixed. Apparently there was a bug in older version of plone.app.content.

**Comment by skleinfeldt** [comment]
Woo hoo! Thank you @cguardia !
