### ISSUE TITLE
Install collective.googleanalytics

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#131]
Would it make sense to do #129 at the same time? And maybe a new version of p.a.imagecropping is available that fixes #125?

**Comment by cguardia** [comment]
Installed the product, but it needs configuration:

https://jazkarta.com/portal_analytics/@@analytics-controlpanel

Tried to upgrade to 5.1, but there's no final version (current release is beta 2). There's a beta 3 coming soon, but it's not yet on the dist.plone.org site. I got a bunch of problems and tried to fix them on my sandbox, but was not successful, so didn't push that change for now.

Will come back to it later, when there's a new release.

**Comment by skleinfeldt** [comment]
Package is installed but I get an error on configuration. Will open a new ticket.
