### ISSUE TITLE
PageSpeed Insights says to enable compression

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#133]
Compressing resources with gzip or deflate can reduce the number of bytes sent over the network.
Enable compression for the following resources to reduce their transfer size by 804.7KiB (72% reduction).

    Compressing https://jazkarta.com/…02-16 00%3A00%3A00/plone-compiled.min.js could save 281.8KiB (71% reduction).
    Compressing https://jazkarta.com/…e.js.jqueryui.custom.min.js?version=None could save 196.1KiB (74% reduction).
    Compressing https://jazkarta.com/…A56%3A21.397496/plone-legacy-compiled.js could save 143.7KiB (72% reduction).
    Compressing https://jazkarta.com/…e++2017-04-04T21:56:22.985219/default.js could save 138.8KiB (71% reduction).
    Compressing https://jazkarta.com/… 21%3A56%3A22.891643/isotope.pkgd.min.js could save 43.9KiB (76% reduction).
    Compressing https://jazkarta.com/…azkarta.plonetheme/jazkarta_theme.js?v=4 could save 521B (60% reduction).

**Comment by davisagli** [comment]
@alecpm says this is a bug in the opsworks configuration for the https vhost in particular, w/r/t mimetypes

**Comment by alecpm** [comment]
This is fixed.
