### ISSUE TITLE
PageSpeed Insights says to Leverage browser caching

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#134]
Setting an expiry date or a maximum age in the HTTP headers for static resources instructs the browser to load previously downloaded resources from local disk rather than over the network.
Leverage browser caching for the following cacheable resources:

    https://js-agent.newrelic.com/nr-1026.min.js (2 hours)
    https://www.google-analytics.com/analytics.js (2 hours)
    https://jazkarta.com/…zkarta.plonetheme/css/jazkarta-icons.css (24 hours)
    https://jazkarta.com/…azkarta.plonetheme/css/jazkarta.css?v=27 (24 hours)
    https://jazkarta.com/…ts/WOFF/OTF/SourceSansPro-Black.otf.woff (24 hours)
    https://jazkarta.com/…ts/WOFF/OTF/SourceSansPro-Light.otf.woff (24 hours)
    https://jazkarta.com/…/WOFF/OTF/SourceSansPro-Regular.otf.woff (24 hours)
    https://jazkarta.com/…WOFF/OTF/SourceSansPro-Semibold.otf.woff (24 hours)
    https://jazkarta.com/…rta.plonetheme/fonts/source-sans-pro.css (24 hours)
    https://jazkarta.com/…etheme/images/GitHub-Mark-Light-32px.png (24 hours)
    https://jazkarta.com/….plonetheme/images/TwitterLogo_white.png (24 hours)
    https://jazkarta.com/…etheme/images/jazkarta-logo-WHITE-01.png (24 hours)
    https://jazkarta.com/…arta.plonetheme/images/jazkarta_logo.png (24 hours)
    https://jazkarta.com/…heme++jazkarta.plonetheme/images/rss.png (24 hours)
    https://jazkarta.com/…azkarta.plonetheme/jazkarta_theme.js?v=4 (24 hours)
    https://jazkarta.com/….js.jqueryui.custom.min.css?version=None (24 hours)
    https://jazkarta.com/…e.js.jqueryui.custom.min.js?version=None (24 hours)

**Comment by alecpm** [comment]
24 hours is plenty cache for theme images and css. If google thinks the GA js should be cached longer, they should fix that :-)
