### ISSUE TITLE
collective.googleanalytics traceback on Save

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#135]
https://jazkarta.com/portal_analytics/@@analytics-controlpanel
Under Plugins add PloneFormGen forms (optional step, seems to throw an error on any Save)
Save

Traceback:

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module plone.z3cform.layout, line 63, in __call__
    Module plone.z3cform.layout, line 47, in update
    Module plone.z3cform.fieldsets.extensible, line 65, in update
    Module plone.z3cform.patch, line 30, in GroupForm_update
    Module z3c.form.group, line 145, in update
    Module plone.app.z3cform.csrf, line 22, in execute
    Module z3c.form.action, line 98, in execute
    Module z3c.form.button, line 315, in __call__
    Module z3c.form.button, line 170, in __call__
    Module plone.app.registry.browser.controlpanel, line 59, in handleSave
    Module collective.googleanalytics.browser.controlpanel, line 91, in extractData

TypeError: argument of type 'NoneType' is not iterable

**Comment by davisagli** [comment]
Fixed
