### ISSUE TITLE
Rename Client to Project [optional]

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#14]
Rename Client content type to Project *IF AND ONLY IF* it is not time-consuming to do.

I've realized that we sometimes do more than one project for the same client (WTA, ISAW), so project is more appropriate. If this is a big pain I'm fine with just changing what it says in the UI!

**Comment by cewing** [comment]
should be fixed now.

**Comment by skleinfeldt** [comment]
Yay! I see projects!
