### ISSUE TITLE
Related Slider ugly on staging

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#144]
Not using the right crop, scrollbar instead of arrows. For example: https://staging.jazkarta.com/projects/the-mountaineers-website

**Comment by alecpm** [comment]
That scrollbar is the new jQueryTools less implementation, it should be more accessible and offer better responsive behavior even if it's a bit less flashy. I think the crop and alignment issues should be fixed now.

**Comment by skleinfeldt** [comment]
Closing this one, remaining issues are on #143.
