### ISSUE TITLE
Display view weirdness related to Mosaic on staging

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#145]
As I click links on staging (things that came in the production clone, not things I've added), I've often been shown a page with just the title plus an error message about rendering the tile. See for example https://staging.jazkarta.com/services/plone-cms/plone-salesforce. True whether logged out or logged in. If I set the Display View to "View Document" the problem goes away, I **think** permanently.

It is as if installing Mosaic made every page think it was supposed to use "Mosaic Layout" instead of "View Document", whereas the opposite is desired.

**Comment by skleinfeldt** [comment]
Possibly related: when I add a Page I get a form where I can fill in Title, Description, and the Related Slider fields - but not Rich Text. I have to save the page, then it prompts me for the Mosaic layout to use. If I select one it puts me into the Mosaic editor. If I X close the popup it puts me into the regular Page editing form.

Maybe standard behavior when Mosaic is installed? Seems odd to assume every page will have a Mosaic layout, so I'm wondering if there is some setting to turn this off that we are missing.

**Comment by alecpm** [comment]
Should be fixed now. With Mosaic installed, the `layout_view` becomes the default.  I've switched that and turned on the `layout_view` for the home page manually. Feel free to turn on the layout view for other pages that should be mosaic as well.

**Comment by alecpm** [comment]
What's interesting though is that if I visit the layout view manually:

https://staging.jazkarta.com/services/plone-cms/plone-salesforce/layout_view

Things seem OK.

**Comment by skleinfeldt** [comment]
https://staging.jazkarta.com/services/plone-cms/plone-salesforce now works for me. Oddly, https://staging.jazkarta.com/services/plone-cms/plone-salesforce/layout_view gave me the "error rendering tile" message a couple times but now is working. Crossing fingers and closing.
