### ISSUE TITLE
Longer interval before logged out

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#147]
I need to re-login a few times a day on both staging and production, which is a little irritating. Can that time interval be increased to 24 or 48 hours?

**Comment by skleinfeldt** [comment]
This is really pretty annoying, upping the priority.

**Comment by alecpm** [comment]
This should be fixed on both.

**Comment by skleinfeldt** [comment]
Awesome - will close next week when I spend time on the sites just to confirm.

**Comment by skleinfeldt** [comment]
Yippee!!
