### ISSUE TITLE
Top nav links go to .../view on staging

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#148]
This makes it impossible to go to the default page for the folder. Compare for example
https://staging.jazkarta.com/services/view (where the SERVICES link goes to)
with
https://staging.jazkarta.com/services/ (shows the default page)

Weird that this changed with the 5.1 upgrade...

**Comment by alecpm** [comment]
For some reason `Folder` was set in the `types_use_view_action_in_listing` registry variable for reasons I do not comprehend. It is fixed.

**Comment by alecpm** [comment]
Apparently I added a migration step 4 years ago to undo that, but it got done again.

**Comment by skleinfeldt** [comment]
:-) Thanks!
