### ISSUE TITLE
Replace huge homepage banner with narrower one

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#149]
Attached. This will probably require
  - Overlaid text pushed down
  - Revisit responsive behavior

Maybe a good idea to address #123 at the same time?

![saxophone_banner-retouched-thinner](https://user-images.githubusercontent.com/1198463/63893872-3feadc80-c9b9-11e9-8365-f8a1144eabc8.jpeg)

**Comment by skleinfeldt** [comment]
Try this on staging with just banner, no text. Any text will be added to the image itself.

**Comment by alecpm** [comment]
I've implemented the larger saxophone as a site wide banner since that was easier than targeting just the homepage. We can tweak it with CSS to set a fixed height depending on the direction we end up wanting to go with it.

**Comment by skleinfeldt** [comment]
Compare https://staging.jazkarta.com/ to https://jazkarta.com/. The banner is smaller but the extra space is now occupied by the blue part above, making the overall header the same height. The idea of this was to reduce that height.

**Comment by skleinfeldt** [comment]
...and that's a problem on Firefox only, Safari, Chrome, iOS on my tiny iPhone 6...

**Comment by skleinfeldt** [comment]
And now that I have logged out this is not a problem. Closing.
