### ISSUE TITLE
Add fields to Client/Project

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#15]
Add Design Credit and Organization text fields.

Add Case Study field which allows selection of a File object on the site.

Add Services multi-select field with the following options (which should be editable on a control panel):
- CMS Implementation
- Web Application
- edX Customization
- Salesforce Integration
- Enterprise Search
- Resources for Scholars
- Cloud Deployment
- Discovery
- Training
- Support

These have been added to the spreadsheet, https://docs.google.com/spreadsheets/d/1wS5ztMXrB1bJMAMSqKxDWzXH3071t0yMBN2elECWkcs/edit#gid=0

**Comment by cewing** [comment]
ready to review on next testing release

**Comment by skleinfeldt** [comment]
All looks good, except that when I choose a file as a Case Study, the view that is supposed to link to it does not work - see http://beta.jazkarta.com/projects/dumbarton-oaks-website. Is that a view problem that needs another ticket @cewing?

**Comment by cewing** [comment]
Once deployed, that last commit should fix this issue.

**Comment by skleinfeldt** [comment]
All better!
