### ISSUE TITLE
Change how Services field on Projects work

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#150]
Currently it is configured on the control panel by giving it a path (like /services) and it dynamically makes the Services list from all the published folder titles in that location.

I am going to be flattening the hierarchy of the site, and the list of services will no longer map neatly to the contents of one folder. Instead we need a list of title/URL pairs, where the title is what shows on the Projects page (and in the edit form) and it links to the URL.

Timing of this needs to be discussed. It is tied to the re-org of Services content I was planning to do on production prior to cloning to a new staging and upgrading. So I think it needs to happen on current production, rather than the 5.1 branch.

**Comment by alecpm** [comment]
I'm not sure I understand this. Is there a reason why this shouldn't be a list of page/folder titles and their urls? It sounds like you want a list of Titles and urls that you manually point to some page in the site which via the url of that page.

**Comment by skleinfeldt** [comment]
I think you got it right when you said it's a list of titles and URLs. I edited the description to hopefully be clearer.

**Comment by alecpm** [comment]
In that case, I don't understand why we shouldn't use e.g. a folder listing to generate this since the URLs are presumably internal to the site and represent content that lives in a folder somewhere.

**Comment by skleinfeldt** [comment]
My reasoning was that the Services vocab would no longer map to objects in a folder. I am trying to flatten the hierarchy of the site, so most of the pages describing Services will be in the /services folder where they will be mixed with the services landing page and pages describing the technologies we work with (mentioned on the new services landing page https://staging.jazkarta.com/services). 

However these new pages and IA are a work in progress. So putting this on hold until things are clearer.

**Comment by skleinfeldt** [comment]
Decided against this, closing.
