### ISSUE TITLE
Mosaic Image Tile

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#151]
Maybe this is a new tile, or maybe this is styling one of the existing tiles (Embed? Rich Text?) It is just an image with a specific crop and a link. It should be an existing image on the site where I'll control the image cropping. 

On the current cover homepage we use the Preview crop for the images. The Mosaic image and blue/green tiles (#139) need to go 4 in the row (instead of 3), and the rows need to extend closer to the left/right edges than the current design. Hopefully that will work?

Doing something quick and dirty on all these new tiles and then getting design feedback is probably the best approach.

**Comment by alecpm** [comment]
The "Existing Content" tile allows you to point at any content and display the image for that content at a specific scale (title and description are optional). I think that should work for this, but we can add additional styling as needed.

**Comment by skleinfeldt** [comment]
This will probably work - https://staging.jazkarta.com/mosaic-homepage. It looks reasonable on Firefox logged in, and terrible on Safari anonymous (the image sizes are larger and overlap) so will at some point probably need some styling love. Leaving this open for eventual styling work, nothing more needed now.

**Comment by skleinfeldt** [comment]
I added `style="border: 10px solid black"` to the field that says "Tile additional styles" for the Go Botany image but it didn't seem to do anything. Some of these will need black outlines, but we might as well make it part of the tile style (like we've done on the Project page) instead of me remembering to add something manually.

**Comment by alecpm** [comment]
I think `border: 10px solid black;` is all you need there.

**Comment by skleinfeldt** [comment]
Tried entering that in "Tile additional styles" on Go Botany image, but still nothing.

**Comment by skleinfeldt** [comment]
FYI entering `border: 10px solid black;` in "Tile additional styles" on an Existing Content tile still does nothing. (Unless my weak eyes are just not seeing it, I added to both Go Botany and Go Orchids tiles.)

That may turn out to be a problem, or it might not because I may decide to use a Rich Text tile containing only an image with link for this use case. The reason being that I may want to use an image that links to a regular page (with no lead image), or I may want to create a special image that links to a Project page, rather than use the Project's lead image. 

I'll leave this open since the "Tile additional styles" don't seem to be working, but it's not a high priority for now.

**Comment by alecpm** [comment]
Sorry, tile additional styles just applies additional classes. So we need to add a new class to the theme JS. On the other hand, we could add a tile style for this border to the Mosaic format menu that could apply to any tile type and would apply to the outermost tile wrapper div.

**Comment by alecpm** [comment]
I've added a tile style to the format menu that should take care of this.

**Comment by skleinfeldt** [comment]
You mean to the Existing Content format menu? That may prove handy, but I've decided to use Rich Text tiles for the "We Love" row use case because it gives me more flexibility - I can use any image I want, and link to anything that I want (a page describing our services, a Project, a News Item, even an external blog post). The Existing Content tile is too restrictive. I can add a black border to the image easily enough by editing source code in TinyMCE. All of the tiles in the "We Love" rows are now done this way.

However, the "We Love" rows look sensible for the 1% using FF on desktop but they look completely bonkers on Safari and Chrome. Can you fix that or do I need to do something?

**Comment by skleinfeldt** [comment]
OOOH! you added Black Border to the Mosaic Format menu! Found it, used it, but it is a bit overkill :-) - see the first row edX tile: https://staging.jazkarta.com/mosaic-homepage

Could you change that to `style="border: 1px solid black;"` please?

And please let me know what needs to happen to have things look sensible on Safari/Chrome.

**Comment by alecpm** [comment]
I've changed the border size. I guess from your note on #139 that the layout issue you were seeing is fixed?

**Comment by skleinfeldt** [comment]
Yes! Looks good and this is all set, closing.
