### ISSUE TITLE
Mosaic tile for Featured Projects 

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#152]
Theme the Mosaic Rich Text tile for use in the Featured Projects row. There will be 2 of them in the row. I can use whatever crop you want (existing or a new one). The image needs to have a border line around it like the images on the Project pages. I can add that in the HTML, just tell me what markup to use.

**Comment by alecpm** [comment]
I would just add `style="border: 5px solid white"` or whatever on whatever tag wraps the image in the WYSIWYG, but we could add a style in the WYSIWYG menu to add a specific type of border if this is likely to be common.

**Comment by skleinfeldt** [comment]
I tried adding that to the `img` tag, and to the `p` tag that wraps the image, but in both cases it got stripped out. Maybe TinyMCE settings need adjustment?

A WYSIWYG menu item for this style would be nice, but not essential.

**Comment by skleinfeldt** [comment]
I also tried adding it to the `img` tag for the Pleiades image here: https://staging.jazkarta.com/services/cutting-edge-research, and it was stripped out.

Should I put it in a `span` tag around the image? Do I need to add `style` to the list of custom attributes to allow on https://staging.jazkarta.com/@@filter-controlpanel?

**Comment by alecpm** [comment]
Yes, adding the style attribute to the allowed tags in the filter control panel should fix it (assuming it's not already in one of the blacklist fields).

**Comment by skleinfeldt** [comment]
Success, adding `style` as an acceptable Custom Attribute in the HTML Filter control panel allowed me to add style as an image attribute in TinyMCE. Worked for rich text mosaic tiles (homepage) and regular pages (https://staging.jazkarta.com/services/cutting-edge-research).

Somehow while editing the VMS Featured Project tile to have a border around the image, the tile slid down and no longer aligns with its neighbor. No idea why or how to fix it. I'm finding Mosaic difficult to work with.

In spite of that: The normal Rich Text mosaic tile will work fine for the Featured Project row, so closing this ticket.

Note to self:
- I used Preview scale for the images in Featured Projects row.
- `style="border: 1px solid black;"` is the correct style setting for image borders.

**Comment by skleinfeldt** [comment]
PS Adding a special WYSIWYG style for an image with a border is a low priority nice-to-have that I'm not even going to make a ticket for.
