### ISSUE TITLE
Can't use Project as an image in TinyMCE

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#157]
Project is listed as an "image type" on the TinyMCE control panel, but Projects do not show up on the image selector widget. True on staging and prod.

Same deal with Team Member.

High priority since it's a bit of a blocker for playing with Mosaic stuff.

**Comment by alecpm** [comment]
This is fixed, the configuration needed to use the internal type name (`jazkarta.project`, `jazkarta.team_member`) rather than the title.

**Comment by skleinfeldt** [comment]
A non-developer admin (me) would never guess that they have to use the internal type name, and wouldn't know where to look that up. Is this problem built into the TinyMCE control panel or is it something about the jaz.com configuration settings? 

If it's specific to jaz.com, is it because of the way our content types are written? If so, is it easily fixed? Because that's the real problem. `<rant>`We should never write content types this way, it is very client-unfriendly. Maybe we need a canonical best practice content type definition somewhere that we use to check all of the custom types that we write against.`</rant>`

The following is mostly a note-to-self, but I would be interested in hearing if a fix is possible on the TinyMCE control panel, and how long that would take. If so I'd consider fixing it on Jazkarta time as long as it wouldn't take longer than 5 hours. 

If this is built into the TinyMCE control panel it's a bug. The fix should have 2 parts:
  1. Make it use the user friendly name
  2. Add to the Image Type help text on the Resource Types tab of the control panel:  _Enter a list of content types which can be used as images. Format is one content type per line. You can find the names of all the content types by going to the Content Settings control panel and looking at the list on the first dropdown. You can find the name of the content type of a particular content item on the Folder Contents view by turning on display of the "Type" column._

**Comment by skleinfeldt** [comment]
@alecpm let me know if it's time consuming or unreasonable to change the jaz.com content types to fix this problem, if that is in fact the cause. If so I'll close this (without even grumbling.)

**Comment by alecpm** [comment]
It's a Plone/TinyMCE issue control panel issue. The correct fix is for the control panel to use a multi-select instead of free text entry of portal type ids, but that's an issue to be filed in Products.CMFPlone.

**Comment by skleinfeldt** [comment]
Thanks for the explanation and you are so right that a multi-select is the right solution. Closing this, will file an issue on CMFPlone.
