### ISSUE TITLE
New Mosaic row format options 

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#159]
Create the following **Row** options on the Mosaic Format menu:
- [x] Green background: uses #80c34f as the background color
- [x] Blue background: uses #205c90 as the background color
- [x] Full width: extends any background color to the edge of the page (aka full bleed)
- [x] Responsive Shrink: Responsive behavior is to shrink tiles, not stack them
- [x] Responsive Drop: Responsive behavior is to drop the rightmost tile

We will need to use white text on top of these colored backgrounds. I can edit source in the rich text editor and add the color pretty easily, probably not worth it to have white font color be on the TinyMCE menu.

**Comment by alecpm** [comment]
These are up on staging for your review. The font color will default to white for content in one of the blue or green mosaic rows (though in edit mode it will still be black, because the editor background is white).

**Comment by skleinfeldt** [comment]
These all work great (well I didn't actually need to use Responsive Drop but used everything else). There are a couple rough edges, will make new tickets.

Pretty close to the new homepage now: https://staging.jazkarta.com/copy_of_mosaic-homepage-3
