### ISSUE TITLE
Error rendering middle bottom portlet on mosaic pages

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#161]
Examples:
https://staging.jazkarta.com/about/team or https://staging.jazkarta.com/about/team/team
https://staging.jazkarta.com or https://staging.jazkarta.com/mosaic-homepage-3
https://staging.jazkarta.com/mosaic-homepage-4

**Comment by alecpm** [comment]
It was a unicode error in the "What We Do" portlet, but there wasn't anything obviously strange in the portlet and resaving it fixed the problem. 🤷‍♂️

**Comment by skleinfeldt** [comment]
Looks good!
