### ISSUE TITLE
Verify all but 2 cover pages are deleted

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#166]
@alecpm I've replaced all but 2 of the collective.cover pages on production with regular pages. The exceptions are the homepage (/homepage) and the team page (/about/team/team-cover). Could you please verify on the ZMI that there are only 2 cover pages left?

Then could you please delete the empty folder https://jazkarta.com/cover-pages-to-delete. I am getting a "Deleting overview" pop up that I'm not familiar with, saying it is a non-empty folder. Sure looks empty to me. Maybe this is a normal, misleading message.

**Comment by alecpm** [comment]
I've seen that "non-empty folder" issue popup when deleting a collection in Plone 5, I think it's because the collection has "contents" that somehow trigger the warning even though they are not actual contents and won't be deleted. I believe it can be safely ignored.

**Comment by alecpm** [comment]
The site search should take care of finding cover pages:

https://www.jazkarta.com/search?advanced_search=False&sort_on=&sort_order=&SearchableText=&advanced_search=True&portal_type%3Alist=collective.cover.content&created.query%3Arecord%3Alist%3Adate=1970-01-02&created.range%3Arecord=min
