### ISSUE TITLE
Harmonize padding around content for mosaic vs non-mosaic pages

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#167]
Non-mosaic pages have inappropriately large amounts of side padding for many desktop sizes.

Mosaic pages have inappropriately small amounts of side padding for many desktop sizes. (In fact content bleeds off the edge at some sizes.)

Find a happy medium and make them both the same as much as possible.

**Comment by alecpm** [comment]
I've adjusted the base width of mosaic and non-mosaic containers to be the same (1140px) and to be a bit smaller than mosaic default (1170px) and a bit larger than the previous non-mosaic default (1050px).

**Comment by skleinfeldt** [comment]
That looks good!

I don't know if this is related, but on my iPhone 6 the Jazkarta logo in the footer is so far to the left it is slightly off the page. If this is not a problem on newer phones, nevermind.

**Comment by skleinfeldt** [comment]
Two tweaks remaining on this:

- [ ] Please adjust placement of Jazkarta logo in footer on small sizes so there is a bit of padding
- [ ] On inner, non-mosaic pages the left alignment of the header logo and body text/title seem to be in sync. Please see if it would be possible to keep them aligned on homepage/mosaic pages as well.

**Comment by skleinfeldt** [comment]
Footer left alignment is perfect on inner pages, wonky on homepage (Mosaic) on my iPhone 6.

Inner page:

![inner-page-footer](https://user-images.githubusercontent.com/1198463/91192628-28c1f600-e6c4-11ea-9388-50d1fbab2832.PNG)

Homepage:

![homepage-footer](https://user-images.githubusercontent.com/1198463/91192666-34adb800-e6c4-11ea-80aa-fb990ff10349.PNG)

**Comment by skleinfeldt** [comment]
Header left alignment and spacing looks perfect on inner pages, not so good on homepage (mosaic) on my iPhone 6.

Inner page:

![inner-page-header](https://user-images.githubusercontent.com/1198463/91193109-be5d8580-e6c4-11ea-866f-fcec46f194db.PNG)

Homepage:

![homepage-header](https://user-images.githubusercontent.com/1198463/91193163-c9b0b100-e6c4-11ea-9f0f-44e014e3dbe1.PNG)

**Comment by skleinfeldt** [comment]
On desktop, header and body are perfectly left aligned at all window sizes I've tried. On homepage/mosaic there are still certain sizes where things get out of whack. This may be too hard to fix though...

![homepage-header-desktop](https://user-images.githubusercontent.com/1198463/91195629-290fc080-e6c7-11ea-8ee9-bfd38c8d2ad8.png)

**Comment by alecpm** [comment]
I don't think the mosaic view ever expands beyond the window width now, except when logged in with the toolbar visible (which complicates the responsive behavior incredibly). The header/non-mosaic container and mosaic container widths seem to match up well at large desktop and mobile and small tablet sizes, but become mismatched at larger "tablet" sizes (between 992px and 1200px).

Customizing the mosaic sizes is going to be tricky, but I think they generally work better than the header sizes. So I'll try to better replicate the mosaic breakpoints in the other containers. We're fighting against a lot of Plone/Mosaic CSS though.

**Comment by alecpm** [comment]
I think I've provided the maximum margin harmonization that I can. The header still does strange things when you're logged in because it doesn't adjust for the toolbar width like some of the other elements do, but it would probably take a couple of hours to get those adjustments right and nobody except you will ever see them.

**Comment by skleinfeldt** [comment]
I know the logged in alignment is wacko! I have to keep reminding myself when I'm working.

Header/body alignment look great on desktop, no more problems on mosaic homepage (https://github.com/jazkarta/jazkarta.com/issues/167#issuecomment-680101594)

The issue with header alignment being perfect on inner pages, a little weird on mosaic homepage on my phone is the same (https://github.com/jazkarta/jazkarta.com/issues/167#issuecomment-680091441) - the way About and News drift off the edge. May be related to #173.

The issue with footer alignment being perfect on inner pages, wonky on mosaic homepage on my phone is the same (https://github.com/jazkarta/jazkarta.com/issues/167#issuecomment-680088521)

On Doug's iPad the Jazkarta logo in the footer right up against the edge of the page (homepage and inner page), just because of how it hits the breakpoint.

All that said this is mostly perfect and the imperfect bits are good enough, closing.
