### ISSUE TITLE
We Love text too big on mobile

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#168]
Using the Background Image tile with H2 text, in a Responsive shrink row format, the text is too big on mobile devices like iPhone 6 and a Motorola Android.

![iphone-6-homepage-screenshot](https://user-images.githubusercontent.com/1198463/89951179-ecd55e00-dbf8-11ea-865a-f5b7598b8133.jpg)

**Comment by alecpm** [comment]
This is up on staging.

**Comment by skleinfeldt** [comment]
Yay!!! Fixed
