### ISSUE TITLE
Reduce size of Sax banner on inner pages

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#169]
According to https://github.com/jazkarta/jazkarta.com/issues/149#issuecomment-622254476 the narrower Sax photo is part of the header site-wide and should be reduced using CSS as needed. On inner pages it should be narrow like it is now on production, for example https://jazkarta.com/services. The full size image should only be shown on the homepage.

**Comment by alecpm** [comment]
This is up on staging.

**Comment by skleinfeldt** [comment]
Perfect. (Question remains about breadcrumbs #175.)
