### ISSUE TITLE
Add packages to buildout

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#17]
Add these packages to the buildout:
- plone.app.imagecropping
- Products.redirectiontool

 We will also us a Javascript faceted search library (Isotope or https://mixitup.kunkalabs.com/), but I gather that doesn't go in the buildout.

Plone 5 compatible versions pinned.

**Comment by cewing** [comment]
Ready for review upon next release to testing

**Comment by skleinfeldt** [comment]
@cewing both add-ons are there, only imagecropping was installed. I installed redirection tool and there were no complaints.

(The add-ons panel says collective.cover needs to be upgraded, tell me when it is ready to do that.)
