### ISSUE TITLE
Question about image crops

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#170]
Staging is using the p.a.imagecropping defined crops in the dropdown on the "add image" dialog. For example `preview 380x255`. Prod is using what looks like the original Plone defined crops on the
dropdown.  For example `Preview (400x400)`. Both get translated in HTML code to `data-scale="preview"`. But in side by side comparisons they look different. Compare
- https://jazkarta.com/services/automated-cloud-deployments/automated-cloud-deployments
- https://staging.jazkarta.com/services/automated-cloud-deployments/automated-cloud-deployments

Is this because of version differences between staging and prod and I should not worry about it?

**Comment by alecpm** [comment]
This is not something to worry about. We customized this crop size on staging because we didn't want the auto-crop to be square I think.
