### ISSUE TITLE
Create a "Testimonial" style with another quote color

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#172]
The `Testimonial` CSS class is used on Project pages and creates the big fat blue quote, for example:
```
    <div class="Testimonial">
    <blockquote>
    <p><a href="......>Blah blah blah</a></p>
    </blockquote>
    </div>
```

Please create a second class (`Testimonial2` or `TestimonialLite` or whatever) just like that, but with the color value of the quote being the light blue `#bdd0e7`.

**Comment by skleinfeldt** [comment]
(This will be used on the new homepage on top of the blue background color, https://staging.jazkarta.com/new_mosaic-homepage-3.

**Comment by alecpm** [comment]
Maybe we should use a unicode symbol (or an SVG) instead of a PNG so we can change the color based on the background. For example:

https://unicode-table.com/en/275D/

Or:

https://www.svgrepo.com/svg/84317/quote

Otherwise we need a new version of the image.

**Comment by alecpm** [comment]
Or:

https://unicode-table.com/en/201C/

**Comment by alecpm** [comment]
I've used the last unicode option for now.

**Comment by skleinfeldt** [comment]
I'm sorry I was offline when you posed those questions and didn't get a chance to respond. I really like the snazzy quote image Leah made and don't like the various SVG options nearly as much. Can you please point me to or email me the image and I'll have Leah make another one in the appropriate color.

BTW changing to the SVG messed up the project page on mobile and desktop, so please be sure to undo that. For example https://staging.jazkarta.com/projects/the-mountaineers-website

![project-page-quote](https://user-images.githubusercontent.com/1198463/91196702-78a2bc00-e6c8-11ea-8e6e-6c6809f74413.PNG)

**Comment by alecpm** [comment]
The quotation mark is here:

https://staging.jazkarta.com/++theme++jazkarta.plonetheme/images/quotation-mark.png

If she has the original and can export an SVG that we can use as a mask to customize color via CSS that would be ideal, but a second PNG with the new color would be fine also. I'll update the styles once we have the new icon.

**Comment by skleinfeldt** [comment]
@alecpm I just emailed you the SVG.

**Comment by alecpm** [comment]
It's in place now. The lighter color will apply automatically if the `Testimonial` class is in a mosaic "Blue" row. Alternatively, you can use `class="Testimonial light-blue"` to use the lighter color in other scenarios where you might want it.

**Comment by skleinfeldt** [comment]
Very nice, thank you!!! There is one nitpick - the quote falls off the left side of the page on pretty much all screen sizes.

![quote-left-edge](https://user-images.githubusercontent.com/1198463/92155413-578f4900-edf5-11ea-8bce-285348be4340.png)

Would it be possible to move that in? In fact it would be good to have a little more breathing room on both left and right - here on the testimonials row, and on the blog row as well. 

![blog-row](https://user-images.githubusercontent.com/1198463/92156425-f49eb180-edf6-11ea-96ac-cf4eb901eb9c.png)

Both use the full width row style. I'm **not** advocating to pull them all the way in it align with the rest of the text, just a bit more space.

Sorry for the never ending tweaks. But I think this may be the last, it's looking great!

**Comment by alecpm** [comment]
Should be fixed now.

**Comment by skleinfeldt** [comment]
It's not worth spending much time on. I was naively hoping that a Full Width row's content container could have slightly wider side margins (which would address both Testimonials and Blog), so you didn't have to special case it.

**Comment by skleinfeldt** [comment]
It still looks the same, but no need to fiddle with this any more. Closing.

**Comment by alecpm** [comment]
The varnish cache needed to be cleared.

**Comment by skleinfeldt** [comment]
Wonderful!!!
