### ISSUE TITLE
Add Breadcrumbs

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#175]
They should 
- Go in the white space between the header and page title, closer to the header than the title
- Use the format "HOME / FOLDER / FOLDER / PAGE" (no house symbol)
- Be all caps
- Use the body text font but smaller
- For the parts that are links, use the normal link colors (including mouseover color) but keep the weight the same as the non-linked text

**Comment by alecpm** [comment]
This is up on staging.

**Comment by skleinfeldt** [comment]
Glad to see the breadcrumbs - but they were supposed to go "in the white space between the header and page title, closer to the header than the title." Was that position problematic? Or maybe you thought it looked better?

**Comment by alecpm** [comment]
Depends on how you define header I guess. It's below the HTML `<header>` element on the page, but I guess you want it below the banner image. Easy enough to fix.

**Comment by alecpm** [comment]
Should be below the banner image now.

**Comment by skleinfeldt** [comment]
Yes, looks great - and Leah likes the grey background. Thanks!
