### ISSUE TITLE
Upgrade production

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#179]
@alecpm here's a start at a checklist, please correct.

- [x] Clone prod to a new site
- [x] Make robots.txt say no crawl
- [x] Delete cover content (Sally)
- [x] Copy new NAOCC and Dallinger Projects from production (Sally)
- [x] Get rid of lots of addons
- [x] Upgrade to 5.1 latest, install latest tesserae, mosaic, custom stuff, collective.googleanalytics
- [x] Create mosaic homepage (Sally)
- [ ] ~~Set up c.googleanalytics~~
- [x] Launch - swap DNS, fix robots.txt
- [x] Get rid of old staging and production (Sally to give green light)
- [ ] ~~Create mosaic team page (Sally)~~

**Comment by alecpm** [comment]
I think we're already on 5.x, but we do need to do some upgrades to get to the latest 5.1.x.

**Comment by skleinfeldt** [comment]
@alecpm is it worth it to try to get to 5.2 latest? Or is that too big a lift. Try it?

**Comment by alecpm** [comment]
I don't think it's a big lift, but there's a very good chance things will break. I suggest saving that upgrade for a later time when we can test it before upgrading.

**Comment by skleinfeldt** [comment]
OK, 5.1.latest it is.

**Comment by alecpm** [comment]
It's up at https://new.jazkarta.com

**Comment by skleinfeldt** [comment]
@alecpm at long last I have deleted the cover content - at least I think i got everything. I also made sure the new site has the latest content from production (the 2 new projects). So good to go for your next steps.

**Comment by alecpm** [comment]
OK, it's back to you now.

**Comment by skleinfeldt** [comment]
Thank you! Will create homepage shortly.

**Comment by skleinfeldt** [comment]
@alecpm mosaic homepage is in place.

**Comment by skleinfeldt** [comment]
Moving c.googleanalytics setup to #180.

**Comment by skleinfeldt** [comment]
We did it! Moving Mosaic page for Team to #181 and declaring victory.
