### ISSUE TITLE
Slider of lead images for a collection

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#18]
I want to put a horizontal slider that shows the lead images for all the things in a collection, on the bottom of selected pages. (A manually operated slider, not auto-sliding behavior.)  For example, 
- For the page describing a service that we offer (CMS Implementation, Support, etc.), show Clients/Projects that use that service
- For a Client/Project, show other Clients/Projects in the same vertical (non-profit, education, etc.), or in the same vertical using the same service
- For a Team Member, show the Clients/Projects the person has worked on

I got this idea from the Digital Loom site, for example:
- http://digital-loom.com/wellesley-college-alumnae-magazine
- http://digital-loom.com/services/research-discovery

I'd like to put such a thing on regular pages, pages for custom content types, and probably landing pages too. So maybe a bottom portlet? Open to suggestions.

On our website we'll be showing collections of Clients/Projects, but it would be nice to make this an open source package that can use the lead images from any content item. (Maybe this already exists.)

BTW I'm not sure "lead image" is the right phrase - the image that goes with the content item.

**Comment by cewing** [comment]
Develop as a package: 
 
* dexterity behavior
* use querystring widget to provide collection-like behavior for any type
* display results as a manual slider of lead images

potential enhancements:

* support using related items or collection-like behavior
* support AT content in addition to dexterity

**Comment by alecpm** [comment]
I've added package to the collective implementing this behavior/viewlet:

https://github.com/collective/collective.relatedslider

It depends on the existing Collection behavior, but can also use the Related Items behavior instead.  Choice of where to get the items from is made on the edit form for a type once the behaviors are applied.

I have applied both the "Collection" behavior (for picking related items based on criteria) and the "Related Slider" behavior to the "Project" type.  You can see it in action here:

http://beta.jazkarta.com/projects/molecule-editor-for-open-edx

**Comment by skleinfeldt** [comment]
Awesome!!! I love the way this works! A minor suggestion: because there are so many widgets that go with it, would it make sense to put it on its own editing tab (schemata) by default?

However I can't set the collection criteria because none of the Project fields (Services, Technology, Industry) are available on the Select Criteria dropdown. Should I make a separate ticket for that?

Also: what's the protocol for whether to put such packages in the collective org vs. in the Jazkarta org? I plan on making a section of the new site to feature our open source contributions with links to each package and it would be nice if they were all under our org. I don't propose to move anything - collective.exhibit, collective.timelines, collective.zoomit are in jazkarta; collective.workspace, collective.citationstyles are in the collective. What I want is to have a policy for the future.

Chime in anyone who has an opinion.

**Comment by alecpm** [comment]
We should definitely have a separate ticket for the indexes and metadata we want to make available via Collections (relevant for the MixitUp stuff as well).  That's just registry configuration, but it's separate from this add-on.

In terms of the tab placement, I would have really liked to put the criteria selection on a separate tab and perhaps eliminate a couple fields.  However, there's currently no way to change the tab that an existing behavior (e.g. the Collection behavior) puts its fields on.  What I could do is make an alternative version of the collection behavior which moves the desired fields out to the Categorization tab or similar.  That might lead to some confusion about the behaviors, but it's probably the best way to clean up the interface.

I don't really have an opinion.  It's probably best if they live in the collective github in cases where we want to make it easy for existing Plone contributors to contribute to the package and the package creator has access to the collective.

**Comment by skleinfeldt** [comment]
Thanks - new ticket coming up for the indexes. For the tabs, the way it is works fine (just the form is a bit long) and given what you've said, I don't think we should change this.

On the collective question, I hadn't thought about the contributor permissions. That settles in my mind that our Plone packages should be in the collective. Thanks!

**Comment by skleinfeldt** [comment]
Reopening this ticket because the relatedslider behavior has vanished from Projects without a trace. Please put it back!

**Comment by alecpm** [comment]
I put it back on the type TTW, but I'll leave this open to remind myself to add it to the FTI in the profile.  Also, we need to make sure the profile doesn't purge behaviors added TTW in future upgrades (assuming that's what happened here).

**Comment by cewing** [comment]
It most likely is what happened. I had a number of FTI changes for projects and team members related to indexing and did an upgrade step to reload type info. I apologize for the hassle. 

c

**Comment by skleinfeldt** [comment]
Thanks for the quick fix. When you add to the FTI in the profile, can you please add to some other content types as well? Team Members, Pages, News Items, Events, and Covers too if that makes sense. I am assuming adding it is easy so that is the list of everything I can imagine using it on. If adding is tedious prune the list to Team Members and Pages.

**Comment by alecpm** [comment]
It's trivial to add it to other types, but it will clutter up the edit forms for those.

**Comment by skleinfeldt** [comment]
I definitely want it for Pages, for example: http://beta.jazkarta.com/about/open-source/jazkarta-contributions/collective-citationstyles/view

**Comment by skleinfeldt** [comment]
Per our conversation, enable related items behavior and relatedslider behavior on Pages and Team Members - but not collections behavior.

**Comment by alecpm** [comment]
This is done now.

**Comment by skleinfeldt** [comment]
Does not work on Team Members yet because Related Items are not enabled.

Works perfectly on Pages, HOWERVER I'm afraid I was wrong and for Pages I really do need relatedslider for collections. On each services page i want to show the Projects that have that service selected, even though it does clutter up the form. I don’t want to have to set related items manually on each service page.

**Comment by alecpm** [comment]
This is done as well.

**Comment by skleinfeldt** [comment]
Works perfectly!
