### ISSUE TITLE
Update SES credentials

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#185]
Update the SES SMTP credentials to "Signature Version 4". If we don't do this, apparently the SES service will apparently start randomly rejecting an increasing number of email requests that use obsolete "Signature Version 2" credentials.

**Comment by skleinfeldt** [comment]
Nevermind, only affects sites whose SES was set up before 2013.

**Comment by alecpm** [comment]
Looks like jazkarta.com doesn't use SES, but uses carlos@jazkarta.com as the SMTP login!

**Comment by skleinfeldt** [comment]
Hmmm is that something we need to change?

**Comment by alecpm** [comment]
@skleinfeldt Maybe! It's not urgent unless you plan to delete that jazkarta.com account.
