### ISSUE TITLE
Remove carlos@jazkarta.com from website

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#190]
From the contact form and any other place an email address would have been entered. 

Replace with support@jazkarta.com.

Also look for website@jazkarta.com and admin@jazkarta.com and replace that with support as well.

**Comment by alecpm** [comment]
This is done. I've removed him from the contact form CC and switched the primary email on that form from sally@ to sales@. Carlos's GMail is still the SMTP login, but I'll fix that when I setup the SMTP via AWS SES.

**Comment by skleinfeldt** [comment]
Thank you!!
