### ISSUE TITLE
Set up SES for jazkarta.com emails

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#191]
We need to stop using SMTP with carlos@jazkarta.com as the email address.

Our GSuite account says website@jazkarta.com is for "Website SMTP". Maybe that was true at one time but I think Carlos' email is now used. In any case we want to get rid of both these email addresses.

**Comment by alecpm** [comment]
This is done, and seems to be working.

**Comment by skleinfeldt** [comment]
Yay, thanks!

I tried the contact form, it sends from support@jjazkarta and to sales@jazkarta. I got the "test email from Plone" to and from support@jazkarta. I got 2 emails Saturday from AWS regarding the SES request, one saying "not enough info" and the second saying we're all set. (Max send rate of 14 messages per second should do it.)

Let me know if there is something else I should test.
