### ISSUE TITLE
Remove carlos@jazkarta.com from New Relic

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#192]
Carlos was set up to receive email on a some New Relic projects - DOaks and UMP for sure, maybe others.

**Comment by alecpm** [comment]
Done. I didn't see him on any alerts for any properties, let me know if you know of any specific alerts he's received recently though.

**Comment by skleinfeldt** [comment]
I sent 2 examples of alerts for DOaks and UMP, but both over a year old. So perhaps this is done @alecpm?

**Comment by skleinfeldt** [comment]
Great, closing
