### ISSUE TITLE
Delete S3 bucket

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#193]
From an email from Alec on 1/11/2021 regarding notification from AWS about S3 buckets configured for public access

> This is not a concern. The bucket is just a local cache of eggs for Plone, which was a useful optimization when we were using ephemeral storage for our Opsworks instances, but we use persistent storage now so it doesn't gain us much. It's also way out of date at this point, so we can probably just delete the bucket.

**Comment by alecpm** [comment]
Deleted.
