### ISSUE TITLE
Colored square cover tile type

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#20]
We need a cover tile for a colored square - Jazkarta blue with top/bottom centered white title text. On mouseover the tile will change color, hide title, and display the description in white text. (Similar to the behavior on the Client/Project faceted search #6.) It must be possible to edit the title and description text and the link that clicking on the tile goes to.

These tiles will be used on the home page and on landing pages. I'll need tiles that say lots of different things, so I'm ditching the idea of icons or photos.

**Comment by cguardia** [comment]
Will the link always be to a piece of content in the site or can it also be some external URL? If a piece of content only, we can use the basic tile and define a style for it.

**Comment by davisagli** [comment]
If it needs to go off-site, we can use a Link content type, no?

**Comment by skleinfeldt** [comment]
It will always be to content on the site.

**Comment by skleinfeldt** [comment]
@cguardia remember about @cewing 's idea of using one of the standard cover tiles? I thought that worked well with internal content and that this would be pretty simple. I really need this soon so I can start creating cover layouts!

**Comment by cguardia** [comment]
Trouble is the basic cover tile puts the link only in the title, so hiding the title means no link is available when showing the description.

**Comment by cewing** [comment]
Could we do a jbot override just of the template for that tile?

**Comment by cguardia** [comment]
Good idea. Will try that first.

**Comment by cguardia** [comment]
This is mostly done, but probably will need some css tweaking, mostly for the vertical centering.

To use it, add a basic tile, then edit it (in layout mode) and select the "Text mouseover basic tile" from the css class menu. You will also want to hide the date in the same form. Save the layout, and go to compose to add a content item for the link.

**Comment by skleinfeldt** [comment]
Yes! I get it!
