### ISSUE TITLE
Responsive cover layout

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#21]
We need a cover layout for the home page, it may also be used on landing pages. It needs to be responsive. It will have a banner tile at the top (#19), and then 2 or 3 rows of square tiles (#20). Similar to the home page design but no news or blog tiles for now.

**Comment by cewing** [comment]
First step is to drag collective.cover into p5 compatibility.  Our branch implementing that is out of date with the current master, so I will rebase to master and fix issues that arise from that.

**Comment by cewing** [comment]
This appears to already be in place using the newly updated collective.cover.  We get three-column layout mixing down to 1-column at widths corresponding to small tablet or large phone size.

**Comment by skleinfeldt** [comment]
I need some instruction on how to use/test this and #22. Will schedule a time.

**Comment by skleinfeldt** [comment]
Very nice, thank you!
