### ISSUE TITLE
Fix problems in collective.cover modals for layout editing

### ISSUE THREAD

**Issue by cewing** [jazkarta/jazkarta.com#22]
the modal dialogs that should appear for exporting layout and editing configuration of tiles and columns are not working properly.  Fix this.

Must be fixed in order to allow work on #21 to be completed.

**Comment by cewing** [comment]
much improvement.  Not quite there yet, but a lot closer.

**Comment by cewing** [comment]
Fixed now.

**Comment by skleinfeldt** [comment]
Haven't tested extensively, but I trust you. Will open another ticket if I run into an issue.
