### ISSUE TITLE
Make "Services" field on Projects into links

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#28]
I didn't think this one through when I requested this field. The Services for a Project need to be displayed as links to the appropriate page describing the service. That means that on the Jaz Contenttypes Settings I need to be able to edit the Services vocabulary and also choose the page that each service should go to.

That sounds complicated and I think we should discuss ...

**Comment by skleinfeldt** [comment]
Maybe the vocabulary could be a list of pages instead of text - get the text from the page titles...

**Comment by skleinfeldt** [comment]
As @cewing pointed out, there is a folder that contains all the pages to be used, so those are the links and the titles.

**Comment by cewing** [comment]
fixed project view to do the right thing in e7801b110aca01cfceb446cc834d9fe26df0b28e

**Comment by skleinfeldt** [comment]
@cewing is this deployed? Do I have to make a configuration change? It doesn't look different than it did...

**Comment by skleinfeldt** [comment]
Woo hoo! I see it now!
