### ISSUE TITLE
Problem with embeds

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#29]
Embeds such as this are not showing, please do the magic settings fix: http://beta.jazkarta.com/news/the-mountaineers-scaling-the-heights-with-plone

Randomly assigned to @alecpm, feel free to switch. Would like this fixed asap please.

**Comment by skleinfeldt** [comment]
In addition to the slideshare embeds, there is this quicktime move: http://beta.jazkarta.com/news/plone-the-movie/view and http://beta.jazkarta.com/images/plone.mov/view

**Comment by skleinfeldt** [comment]
It looks to me like Slideshare is moving away from their old iframe way of doing things, they no longer provide this type of code which includes an embed code. So it would be good to move to oembed for Slideshare in the future (http://www.slideshare.net/developers/oembed). However I don't want to go back and edit all the Slideshare news items for that right now.

**Comment by alecpm** [comment]
This should be working now.

**Comment by skleinfeldt** [comment]
Yay!
