### ISSUE TITLE
Adjust spacing between description and body

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#3]
See for example /about and compare to mockup.

**Comment by alecpm** [comment]
I think this is done.  There's not really a visible description on /about now, but the padding is a bit more like the mockup.

**Comment by davisagli** [comment]
FWIW some space was also added in barceloneta earlier today https://github.com/plone/plonetheme.barceloneta/commit/dff4b5e1782de5c1892dee281d116d85768e6ee5

**Comment by alecpm** [comment]
Ah, perhaps that explains why the difference I was seeing was so subtle :-)  I bumped it up a little from that.

**Comment by skleinfeldt** [comment]
Looks good, thanks! At some point we'll want to pin versions so things aren't moving targets - sometime next week.
