### ISSUE TITLE
Editable footer text

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#30]
We should be able to easily change the footer text without code/static HTML changes. Please set this up however it should be set up in P5 (footer portlet or viewlet or something?)

Possibilities: I may decide to simplify the footer, just using the contact info. If I stick with the current 3 column design, the right 2 columns should be hidden on mobile.

**Comment by davisagli** [comment]
I added some static text portlets to the footer portlet area, which you can fill in. They'll be styled correctly the next time someone deploys (or @alecpm @cewing @cguardia feel free to give me access to deploy)

**Comment by skleinfeldt** [comment]
Awesome @davisagli thank you!
