### ISSUE TITLE
Industry field should be multi-select

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#32]
Oops, my mistake, the Industry field on Project needs to be multi-select, not single select

**Comment by skleinfeldt** [comment]
@cguardia I really need this!

**Comment by cguardia** [comment]
Done. Sorry for taking so long to get to this one. My brain was totally overloaded last week.

**Comment by skleinfeldt** [comment]
I got a traceback trying to save http://beta.jazkarta.com/projects/go-orchids/  Also look at that field on the view of any project, it is rather amusing...

**Comment by cewing** [comment]
looks like we need an upgrade step that migrates the current projects so that single values already saved become lists of one item.

**Comment by cguardia** [comment]
Should be working now.

**Comment by skleinfeldt** [comment]
Huzzah!!
