### ISSUE TITLE
Add stuff to Project view

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#33]
Oops, forgot these...

Directly underneath the title add:

[list of industries, comma separated]
Client: [organization]
Location: [address]
Technology: [list of technologies, comma separated]

(Eventually the industries and technologies will be links to the project listing/filtering page.)

If the bottom slider is enabled, put a header line "Similar projects" above it

Some basic styling adjustments:

- Fix indentation problem on Description and first View Website
- Put one of those long dashes (—) in front of Testimonial Source

**Comment by alecpm** [comment]
These issues should be addressed

**Comment by skleinfeldt** [comment]
Awesome awesome awesome. So much better!

I made an error though by not explaining the "industry" field. Can you change it to:

Project Type: [list of industries, comma separated]
Client: [organization]
Location: [address]
Technology: [list of technologies, comma separated]

Also, the values are not appearing on the same line as the title, can that be fixed?

**Comment by alecpm** [comment]
There's CSS to put them on the same line that's working locally, but there's some aggressive caching that seems to keep it from working in production.

**Comment by alecpm** [comment]
This has been fixed and the CSS is finally refreshed.

**Comment by skleinfeldt** [comment]
Looks great!
