### ISSUE TITLE
Replace Plone movie

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#36]
Replace this old movie from 2012 with the new one we made for Pycon: http://beta.jazkarta.com/images/plone.mov/view

**Comment by cewing** [comment]
@skleinfeldt are you certain you want this?  It's not really a movie meant for watching end-to-end.  More like a bit of eye-catching background noise intended to get attention from passers-by at the conference.

**Comment by skleinfeldt** [comment]
@cewing if you read the news item it is used on, you'll see the context it is used in. I don't intend to display it anywhere else, just provide it for download. http://beta.jazkarta.com/news/plone-the-movie/view

**Comment by cewing** [comment]
@skleinfeldt got it.

**Comment by davisagli** [comment]
Btw we should probably use something like youtube that has an html player, for compatibility with mobile.

**Comment by skleinfeldt** [comment]
@davisagli oh you are so right. @cewing let's do the easiest possible thing here. I can unpublish that news item and close this ticket for now and we can do the youtube thing when we have a bit more breathing room?

**Comment by cewing** [comment]
yes please.

**Comment by skleinfeldt** [comment]
Roger, retracted.
