### ISSUE TITLE
Metadata we want to make available for Collections and search

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#38]
I think this is now defined correctly on the content types spreadsheet, https://docs.google.com/spreadsheets/d/1wS5ztMXrB1bJMAMSqKxDWzXH3071t0yMBN2elECWkcs/edit#gid=0

The following custom fields should have their own selectable field indexes

- Projects: Industry, Technology, Services, Team, Launch Date
- Team Member: Technology

The following should be part of Searchable Text

- Projects: Organization, Address, Design Credit, Testimonial, Testimonial Source
- Team Member: Address, Musical Instrument

**Comment by cewing** [comment]
@skleinfeldt for the team member type, do you want **only** the address and musical instrument fields to be part of the searchable text, or also the title, highlight and bio?

**Comment by skleinfeldt** [comment]
Sorry this was unclear. Yes, also name, highlight and bio, aka title, description, and body - the idea being to keep searchable text behavior on the OOTB fields that normally have it.

**Comment by cewing** [comment]
This should now be implemented, deploying as I write this.

**Comment by skleinfeldt** [comment]
Need to bring back #18 before I can test this.

**Comment by skleinfeldt** [comment]
Forgot to close this yesterday, was using it for hours. Awesomeness!
