### ISSUE TITLE
Fix your listing

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#40]
All team members (except Chris, no compatible photo yet) have been added: http://beta.jazkarta.com/about/team I divided the current jaz.com entries between highlight and body text without too much thought. Please fix your own listing (and feel free to suggest fixes for others).

- Please make yourself an account on the site with your first/last name so attribution of edits is meaningful
- Adjust the length/content of the highlight/description, we need 1-2 lines on the listing page
- Update/change/improve the body text
- Make sure I got your musical instrument and technologies right
- For site URL, how about if we all use our twitter feed (I claim Jazkarta's), that would be nicely consistent
- Let me know if you don't like the photo I chose

@alecpm , @cewing , @cguardia , @davisagli , @natea please comment here when you are done, and assign it to the next person.

**Comment by natea** [comment]
There seems to be an issue on mobile with the text overlapping the photos.
See attached screenshot

On Tuesday, September 15, 2015, Sally Kleinfeldt <notifications@github.com>
wrote:

> All team members (except Chris, no compatible photo yet) have been added:
> http://beta.jazkarta.com/about/team I divided the current jaz.com entries
> between highlight and body text without too much thought. Please fix your
> own listing (and feel free to suggest fixes for others).
>
>    - Please make yourself an account on the site with your first/last
>    name so attribution of edits is meaningful
>    - Adjust the length/content of the highlight/description, we need 1-2
>    lines on the listing page
>    - Update/change/improve the body text
>    - Make sure I got your musical instrument and technologies right
>    - For site URL, how about if we all use our twitter feed (I claim
>    Jazkarta's), that would be nicely consistent
>    - Let me know if you don't like the photo I chose
>
> @alecpm <https://github.com/alecpm> , @cewing <https://github.com/cewing>
> , @cguardia <https://github.com/cguardia> , @davisagli
> <https://github.com/davisagli> , @natea <https://github.com/natea> please
> comment here when you are done, and assign it to the next person.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jazkarta/jazkarta.com/issues/40>.
>


-- 


Website: http://www.appsembler.com
Blog: http://www.appsembler.com/blog
Twitter: http://twitter.com/natea
LinkedIn: http://linkedin.com/in/natea
Phone: +1 (617) 702-4331

**Comment by skleinfeldt** [comment]
We haven't made a final view for this yet, The current view is a placeholder until we get design input from Leah.

**Comment by alecpm** [comment]
Done.

**Comment by skleinfeldt** [comment]
Thanks @alecpm ! I made additional edits, please review (more recent work, links to your os contributions pages, links to relevant services pages.) 

This applies to everyone: check all links on your listing, the ones to our projects are usually broken. Also remove external links - we'd like to keep people on our site! When talking about work involving Solr, Salesforce, training, opsworks, bibliographies or other specialized academic features, please work in a link to relevant services pages: Enterprise Search, Salesforce Integration, Training, Cloud Deployments, Resources for Scholars.

**Comment by skleinfeldt** [comment]
@cewing please add something about edX and bibliography work to your listing. @cguardia you could add edX too.

**Comment by skleinfeldt** [comment]
Everyone: you can also mention and link to your conference talks that are here: http://beta.jazkarta.com/news

**Comment by skleinfeldt** [comment]
Everyone: I have added as related items your jazkarta projects, please make sure I didn't forget anything. ( @cguardia I didn't really try to put in all of yours, that would be almost everything! Feel free to add more.)

**Comment by cewing** [comment]
Still need to make links to talks.  Should we also list open-source contributions that are not part of our Jazkarta work, @skleinfeldt?

**Comment by skleinfeldt** [comment]
Feel free to mention your other os contributions in the body of your text, but for now I don't think we should worry about making new pages for them.

**Comment by skleinfeldt** [comment]
@cewing , @cguardia , @davisagli , @natea please review you pages and comment here that you have done so.

**Comment by cewing** [comment]
@skleinfeldt I have reviewed my listing and am satisfied with the state in which it currently appears.

**Comment by davisagli** [comment]
Mine's good.

Random idea, maybe we should have a link to our github profiles?

**Comment by skleinfeldt** [comment]
@davisagli that's a great idea! Maybe a new field and add it to the view? Let's hold on that until after the conference though...

@cguardia how about adding the O'Reilly Python web frameworks booklet? And being release manager for Substance D?

**Comment by alecpm** [comment]
@cguardia also your ZODB book.

**Comment by cguardia** [comment]
Ok, added your suggestions. Thanks.

**Comment by skleinfeldt** [comment]
Yay!!
