### ISSUE TITLE
Too sticky title when navigating folder_contents

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#41]
Go to a lower level folder contents, for example http://beta.jazkarta.com/about/team/folder_contents. Click on one of the parent folders above the table, for example About. The table refreshes, the URL changes, but the Title does not change (in the example, it still says Team).

If this is a Plone bug please fix in Plone.

**Comment by davisagli** [comment]
Johannes has recently been working on fixing this in Plone, so I'm inclined to close this issue even though it's not fixed in our site yet.

**Comment by skleinfeldt** [comment]
Sounds good to me!
