### ISSUE TITLE
Portlet management page "Back" button

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#44]
When editing portlets there is no "Back" button to get back to where you were before clicking on manage portlets. You have to edit the URL in your browser to do that. I'm talking about the page .../@@topbar-manage-portlets/plone.rightcolumn

**Comment by davisagli** [comment]
Probably makes more sense to file Plone bugs in the CMFPlone tracker

**Comment by cewing** [comment]
@davisagli: it's not always completely clear that a bug is in CMFPlone or in a bad interaction with something in our packages.  I believe @skleinfeldt wants us to review this type of bug and push it upstream (and fix it) if it is in fact a problem in an upstream package.

**Comment by davisagli** [comment]
This was fixed in Plone (the button says "Return" with an arrow)
