### ISSUE TITLE
Traceback on OOTB news and events 

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#45]
The Collection (news aggregator) that came OOTB with the newly created Plone site throws an error on edit. I moved it here: http://beta.jazkarta.com/old-news/aggregator/view - click edit.

Similarly the containing folder - http://beta.jazkarta.com/old-news/folder_contents - throws an error if you add a News Item to it.

Same thing is true for OOTB events http://beta.jazkarta.com/events/folder_contents 

Perhaps this is because these folders are configured to use, and come with, old-style collections, and yet old-style collections are not installed? In which case the standard add plone site should use new-style collections...

**Comment by davisagli** [comment]
They are new-style collections. This is a Plone bug that's already been fixed in master: https://github.com/plone/Products.CMFPlone/issues/754

**Comment by skleinfeldt** [comment]
Sweet! In that case I'll close.
