### ISSUE TITLE
Proofread open source contributions

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#46]
@alecpm , @davisagli , @cewing please look over the pages for your respective Jazkarta team open source contributions to make sure everything is accurate. Collective.workspace needs an example; I used the blog post because I didn't think any Mntrs rosters were publicly viewable. http://beta.jazkarta.com/about/open-source/jazkarta-contributions/

**Comment by skleinfeldt** [comment]
@cewing ping - proofread and assign to david. Please give me the url for the new isotope add-on so I can write that page.

**Comment by cewing** [comment]
Mine look fine, I think.  I've added a page for [collective.isotope](http://beta.jazkarta.com/about/open-source/jazkarta-contributions/collective-isotope).

Assigning to @davisagli now.

**Comment by davisagli** [comment]
Looks good to me.

**Comment by skleinfeldt** [comment]
Thanks all! and thanks for the isotope page @cewing!
