### ISSUE TITLE
Add Plone resources

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#47]
Everyone please post your favorite Plone resources here so I can add them to the relevant page: http://beta.jazkarta.com/about/open-source/plone-resources

**Comment by davisagli** [comment]
What's the audience? Developers, or potential Jazkarta clients who want to know more about our favorite technologies?

**Comment by skleinfeldt** [comment]
I would say all comers - developers (especially ones not "in the know"), potential clients, current clients, anyone using Plone. Nate used to maintain such a page back in the day and it was the most popular page on the Jazkarta site: https://web.archive.org/web/20080307041827/http://www.jazkarta.com/technology/technology/plone-technology and the 3 links at the bottom. Actual articles would be great if there are any recent ones :-(

The idea here is both to attract traffic and potential customers to our site *and* provide a service to the community.

**Comment by davisagli** [comment]
- plone.com - official Plone marketing site with demos, success stories, providers
- docs.plone.org - Plone documentation
- community.plone.org - Plone community forum
- planet.plone.org - aggregator of Plone-related blogs
- http://webchat.freenode.net/?channels=#plone - Plone IRC chatroom

**Comment by davisagli** [comment]
The ones you've already got are great too.

**Comment by skleinfeldt** [comment]
Thanks @davisagli this good to go I think. We can always add more.
