### ISSUE TITLE
Django resources

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#48]
Everyone please post your favorite Django resources here so I can add them to the relevant page: http://beta.jazkarta.com/about/open-source/django-resources

**Comment by davisagli** [comment]
- https://en.wikipedia.org/wiki/Django_(web_framework)
- https://www.shoop.io/blog/25-of-the-most-popular-python-and-django-websites/
- https://www.airpair.com/python/posts/django-flask-pyramid

**Comment by cguardia** [comment]
https://www.djangopackages.com/

**Comment by skleinfeldt** [comment]
Thanks, good enough for a start.
