### ISSUE TITLE
Pyramid resources

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#49]
Everyone please post your favorite Pyramid resources here so I can add them to the relevant page: http://beta.jazkarta.com/about/open-source/pyramid-resources

**Comment by davisagli** [comment]
- introduction: http://trypyramid.com/
- Pylons Project, the organization that develops and maintains Pyramid: http://www.pylonsproject.org/
- Pyramid documentation: http://pyramid.readthedocs.org/en/latest/
- Pyramid on github: https://github.com/Pylons/pyramid
- http://www.sixfeetup.com/blog/pyramid-for-rapid-development-projects
- https://www.airpair.com/python/posts/django-flask-pyramid
- interview with the creator of Pyramid: http://talkpython.fm/episodes/show/3/pyramid-web-framework

**Comment by skleinfeldt** [comment]
Thank you!
