### ISSUE TITLE
Slider Title field for relatedslider

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#54]
Even though it will mean cluttering the edit form even more, I think we need to add a "Slider Title" field to go with relatedslider. I've tried working around this by putting the title in the Page body (see http://beta.jazkarta.com/services/plone-consulting/plone-support), but it doesn't look connected, and it would be impossible to theme as part of the slider (like for example http://www.digital-loom.com/services/web-design-branding).

**Comment by alecpm** [comment]
This has been added to the relatedslider.

**Comment by skleinfeldt** [comment]
Works!

Judging by the (very subtle!) red dot, Related Slider Title is required. That's fine for our site, but may not be the best choice for the general case.

**Comment by alecpm** [comment]
I intended to make it optional (as the field description indicates), but somehow typed True instead of False.  Thanks.

**Comment by skleinfeldt** [comment]
Haven't tested since not deployed yet, but I trust you. Moving on.
