### ISSUE TITLE
Dimensions of banner tile

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#55]
@davisagli what are the exact dimensions that the image for the banner tile should be please? (clearly I got it wrong!)

**Comment by davisagli** [comment]
width: wide enough that it doesn't look bad when stretched across the entire window on a large display
height: your choice, but I need to fix some css so it works right

**Comment by davisagli** [comment]
css fixed

**Comment by davisagli** [comment]
I do like the shiny. :saxophone:

**Comment by skleinfeldt** [comment]
Looks good (at least front-page does!)
