### ISSUE TITLE
Banner tile text should not be required

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#56]

**Comment by davisagli** [comment]
Are we not going to have text there? If not I think we should use a smaller (less tall) banner image, so that it doesn't push the actual content below the fold.

**Comment by davisagli** [comment]
fixed

**Comment by skleinfeldt** [comment]
Works, thanks. Agree about the height, I want to mock up various things to get Leah's input. However I am now totally blocked doing that by #59...
