### ISSUE TITLE
What's the difference between homepage and front-page?

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#58]
Cris and I added homepage as a training exercise. We added a cover with the Jazkarta layout. We added a row at the bottom and put 3 columns with Basic tiles in them, and then we deleted that row. Then we added the sax image to the banner and added content to the first basic tile. The result looks very different than the front-page you added. We messed around with the banner tile, banner col, and banner row CSS settings but no joy. 

I have now done a side by comparison of every Layout and Compose setting for front-page and homepage, and as far as I can tell they are the same. They also seem to use the same sax image. 

Why does homepage look like crap?

**Comment by skleinfeldt** [comment]
Oh wait! They are not the same, homepage has "Default" for the row and col CSS class, whereas front-page has blank. And now there is no way to choose a blank for homepage. (But maybe if we had never changed it, it would have stayed blank.)

Is this a bug, not being able to change the class back to blank? If it is hard to fix it is low priority, I can just be careful next time.

**Comment by davisagli** [comment]
The diazo rules only work if the row and column have no class. And like you said there's no way to remove the Default class. I had to make a new row and move the tile there.

David Glick
(mobile)

**Comment by skleinfeldt** [comment]
Thanks for the confirmation, now I know how to fix this if I mess up again! I made 2 variants of the homepage, one with text and one without. Reviewed with Leah, and we both liked no text and agreed about reducing the height. Front-page now has that. (Still a placeholder image though.)

Does not being able to revert to blank seem like a cover bug? If so maybe I should file a ticket?
