### ISSUE TITLE
Need Project listing view for faceted search

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#6]
The page where all our projects are listed will be a faceted search (which will be done in Javascript, something like Isotope or https://mixitup.kunkalabs.com/) where Projects can be filtered by Industry, Service, and Technology. The listing for each Project will consist of its image which will change to a solid color and display the Title and Description on mouseover. (In our theme we will probably drop the Title field but the add-on should provide both.) The image will be linked to the Project page. The images will be displayed in a 3 column grid. The grid needs to be responsive, collapsing from 3 to 2 to 1 just like the tiles.

This should be developed as a new open source Plone add-on.

[I wrote the following back in April and not sure if relevant: "Question whether this will work better if we replace the image field on the content type with lead image behavior."]

**Comment by cewing** [comment]
This is now installed and ready for review.  See http://beta.jazkarta.com/projects/project-collection for an example in action.

**Comment by skleinfeldt** [comment]
So awesome. I opened some tickets to adjust styling but the functionality is working nicely.
