### ISSUE TITLE
Another adjustment to border

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#60]
Meaning the padding around the header, footer, and body.

Move the Jazkarta logo to the right and the body to the left, splitting the difference between them. Make the vertical part of the j in the jaz logo line up with the title/body. Make sure the right side of the nav tabs respects the same spacing.

**Comment by alecpm** [comment]
I think I've got this set, but let me know if you see any discrepancies.

**Comment by skleinfeldt** [comment]
This looks great as anonymous, but logged in the body now lines up beneath the K in Jazkarta instead of the J.

Not a high priority, more of an FYI.

**Comment by alecpm** [comment]
I'm not seeing that here, toolbar expanded or no.

**Comment by skleinfeldt** [comment]
FWIW it is a problem on FF when logged in.
