### ISSUE TITLE
New colors

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#64]
Implement new site colors. On the new design:

- The darker blue is R=32 G=92 B=144
- The lighter blue is R=102 G=153 B=203
- The green is R=115 G=236 B=54 (try this, although we might decide it's too neon. If so we'll go back to R=128 G=211 B=79)

General rules:

- Titles are the light blue
- Links are the light blue
- Link rollover color should be green
- NO UNDERLINES on links

**Comment by alecpm** [comment]
These should all be in place.

**Comment by skleinfeldt** [comment]
Some changes from Leah:

- Go back to the less neon green (R=128 G=211 B=79)
- Titles are the DARK blue
- Links are the DARK blue
- Link rollover color should be the LIGHT blue

**Comment by alecpm** [comment]
These changes are also done now.

**Comment by skleinfeldt** [comment]
Groovy. One bit got lost in the shuffle: Link rollover color is still green, it should be the light blue. Very low priority, and if it's disruptive, or if you tried it but didn't like it, then never mind, just close the ticket.

**Comment by skleinfeldt** [comment]
And just noticed - there are underlines on the link rollovers on the basic tiles, there should be no link underlines anywhere. Visible on http://beta.jazkarta.com/front-page/view.

**Comment by skleinfeldt** [comment]
@alecpm reminder: remove link underlines per last comment, and either do or do not change link rollover color to light blue per second to last comment, and close this ticket.

**Comment by skleinfeldt** [comment]
@alecpm I found a reason to change  the link rollover color to light blue - the rollover color is used on the relatedslider arrows and the green looks odd there.

**Comment by skleinfeldt** [comment]
@alecpm another reminder to remove link underlines on rollover, see http://beta.jazkarta.com/services/training/plone-training.

Also please change the rollover link color to the light blue.

**Comment by alecpm** [comment]
I'm not seeing any link underlines, but the rollover color should be fixed.

**Comment by skleinfeldt** [comment]
Really, I did see the underlining! But it's gone now - much have been something cached.

Thanks!

**Comment by skleinfeldt** [comment]
Aha, there's the underline - when using a link in a rich text tile. See the homepage.

**Comment by alecpm** [comment]
Should be fixed now, the underline was showing up on links in headings.

**Comment by skleinfeldt** [comment]
Yesssss...

**Comment by skleinfeldt** [comment]
Oh dear - an unintended side effect - the "Contact" button now goes blue on rollover, it should continue to be green.

**Comment by alecpm** [comment]
Should be fixed.

**Comment by cguardia** [comment]
Fixed indeed.

**Comment by skleinfeldt** [comment]
Yay!
