### ISSUE TITLE
New header

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#65]
See new design. The header is now blue with a white logo and green stripe. (The sax image is still a cover tile.)

- The darker blue is R=32 G=92 B=144
- The lighter blue is R=102 G=153 B=203
- The green is R=115 G=236 B=54 (try this, although we might decide it's too neon. If so we'll go back to R=128 G=211 B=79)

For the Nav:
- On rollover the Get a Quote/Contact thing reverses green/white colors
- On rollover the nav tab is green
- The nav tab for the active page/section  is the lighter blue

**Comment by skleinfeldt** [comment]
This looks great! A tweak:

- Switch back to the less neon green, R=128 G=211 B=79

And one outstanding item:

- Different styling on the Contact nav item. It should say whatever the nav item says, in this case "Contact", but be styled like the "Get a Quote" element in the design. The rule for this can be whatever is the last nav item.

And there is ticket #80 for the different header everywhere except the homepage.

**Comment by alecpm** [comment]
This is done.

**Comment by skleinfeldt** [comment]
Brilliant.
