### ISSUE TITLE
Footer icons

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#69]
We need the Twitter, Github, RSS, and Email icons to use in the footer (below the contact info, the links are there.) Is there something special I should ask Leah for?

**Comment by skleinfeldt** [comment]
Let's try this:

- https://github.com/logos - if possible (if provided), use a white version of the mark with transparent background, if not use the octocat
- https://about.twitter.com/company/brand-assets - use the white bird with transparent background
- http://www.feedicons.com/ - use a white version with transparent background
- email icon - use something simple, white against a transparent background

Images and links are in the footer portlet, files need to be put in the static directory (or somewhere) and this HTML uncommented.

This is not a high priority ticket, but it would be nice to have these icons/links. @davisagli maybe you could take this one to do when you have a chance?

**Comment by davisagli** [comment]
done

**Comment by skleinfeldt** [comment]
Awesome!
