### ISSUE TITLE
Need Team Member view

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#7]
Lay it out like this for now, don't sweat the styling.

    +-----------+
    | Image     |  Sally Kleinfeldt
    |           |  Orange, Massachusetts
    |           |  Piano
    |           |
    +-----------+
    
    Highlight blah blah blah
    
    Bio blah blah blah

**Comment by cguardia** [comment]
On the beta site now.

**Comment by skleinfeldt** [comment]
As for #8, good enough for now, will open a new ticket when we make styling adjustments. Thanks!
