### ISSUE TITLE
Delete an exported cover layout

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#71]
Is it possible to delete an exported cover layout? It turns out that the original one @cewing made (Jazkarta Cover Layout) is unusable. The diazo rules only work for covers if the row and column have no class. And if a row or column gets assigned a class, there's no way to revert it to having no class. You just have to delete the row and start again. (See #58)

If there is not a way to delete it, that would be good feedback for Hector. I can imagine it would be complicated to allow changing one, so it should at least be possible to delete (so you don't use a bad one by mistake).

**Comment by cewing** [comment]
It can be deleted via the registry control panel. But it is non-trivial. Sorry I messed up the first one.  We can fix it in an upcoming upgrade.

**Comment by skleinfeldt** [comment]
Don't give it another thought (and no need to apologize! It was not obvious how to set it up.) It's not really a problem having the old one around. I will add this to my list of feedback to give to Hector, and close this ticket.
