### ISSUE TITLE
New header

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#73]
Implement new header styling. See new design. Note that Jazkarta logo in the footer is white.

Colors:

- The darker blue is R=32 G=92 B=144
- The lighter blue is R=102 G=153 B=203
- The green is R=115 G=236 B=54 (try this, although we might decide it's too neon. If so we'll go back to R=128 G=211 B=79)

Behavior:

- On rollover the Get a Quote/Contact thing reverses green/white colors
- On rollover the nav tab is green
- The nav tab for the active page/section  is the lighter blue

**Comment by alecpm** [comment]
Aside for the get a Quote/Contact form, this is implemented.

**Comment by alecpm** [comment]
We don't have a logo with the text in white, AFAIK so I've left the current light blue one in place for now.  Also, I can't say I'm a fan of the neon green.

**Comment by davisagli** [comment]
The tile mouseovers with white text on a neon green background are too hard to read.

**Comment by skleinfeldt** [comment]
Great! I should be getting the white logo from Leah soon. And yeah, that neon green is a bit overly neon. But let's leave it in place until Leah has a chance to look.
