### ISSUE TITLE
Basic tile with images

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#74]
The team page now uses a cover with Basic tiles with images: http://beta.jazkarta.com/about/team. Not bad! But needs these minor adjustments.

- It is ignoring the image scale I selected on the Layout editing page (thumb). If there is some other way I should be setting this let me know.
- It should have CSS adjustments to behave like the colored variant: hide the title, and on mouseover turn green and show the title.
- As on #57, the entire tile should be the link, not just the text, and there should be no mouseover-underline behavior on the text.

**Comment by skleinfeldt** [comment]
BTW the Basic tiles are currently set to -Default- style on the Layout page, I tried Image with Mouseover and that was no better.

**Comment by cguardia** [comment]
The text tile hides the *description* and shows it on mouseover. Here, do you want the title hidden? Originally the title was supposed to be shown at the bottom, with the description hidden, then on mouseover the description would show over a faded image.

**Comment by skleinfeldt** [comment]
You are right, this is different from the text tile - it would hide the title and show it on mouseover (instead of the description) and it would not show the description at all.

Sorry for the inconsistency - will that be a problem?

**Comment by cguardia** [comment]
No problem, just making sure.

**Comment by cguardia** [comment]
One more thing, the image was set up to be 100% width, which is why the tile ignored your scale. If you want to use different scales, I suppose I should try to center the image on the tile?

**Comment by cguardia** [comment]
Finally, any height and width requirements for the tile (text tile is 380x255).

**Comment by cguardia** [comment]
This is done. Check it out and let me know your answers to my last questions.

**Comment by skleinfeldt** [comment]
Nice. You were right to assume centering the image. I have one question - why is Alec's image so fuzzy? I thought it was cropped like all the others, so wondering if there is some underlying problem?

**Comment by skleinfeldt** [comment]
Alec's image is also a different size.

**Comment by alecpm** [comment]
The image size is a setting in the layout.  However, my image is the only landscape one, and for some reason this view is not using the crops from the cropping tool, but simply scaling the image to fit the width.  I'll update the image lookup code to use the right urls to get the expected crops.

**Comment by alecpm** [comment]
Nevermind, since it's not using the content object (you could just drop the team members on this tile I think), it can't use the crop.  You need to upload an image with the correct crop.

**Comment by skleinfeldt** [comment]
@alecpm I did drop the team members onto those tiles - ? 

But this is a short term problem, we will be getting correctly cropped images, so no need to do anything about this right now.

**Comment by alecpm** [comment]
It looks like it copies the image into the tile storage, so no crops are used in the basic tile :-(

**Comment by skleinfeldt** [comment]
Well geez! Sounds like something that should be fixed in cover. I'll add it to my list of Hector feedback.

**Comment by alecpm** [comment]
I don't think they'd consider it a bug.  The Basic tile isn't a reference to another tile, it's a bag of data that you can conveniently populate with data from a piece of content.  We could customize our version of the tile to use the original image url directly if available (even though the image is already copied to the other tile).

**Comment by alecpm** [comment]
Just in case though, I submitted a pull request with a simple fix.  

https://github.com/collective/collective.cover/pull/552

Instead of having the tile pull the full sized image and perform the cropping and scaling itself, if the tile has a specific scale set it will just pull that scale from the content (resulting in a correct plone.app.imagecropping crop and less duplicate image data).  I've included this patch in our local Plone 5 compatible branch of collective.cover.

**Comment by cguardia** [comment]
This might come in very handy to the cover team, as they've have been having problems with blob data not being cleared after deleting covers with this kind of duplicate data.

**Comment by alecpm** [comment]
This won't help with that, it's still copying the blob data, but it's at least just a scaled down image (with proper cropping).

**Comment by skleinfeldt** [comment]
Reopening to make one tweak: @cguardia please make the green color on mouseover be solid, not transparent.

As for the discussion about copying content images vs. using in place, it seems like there could be an argument to do the latter instead of the former - simpler, faster implementation, tracks content changes so more intuitive, use content scales/crops, saves space. Maybe there should be 2 tile types - one that you drop content on, and one that you upload a new image to.

In any case, do we need an upgrade step or something for our basic tile images to pick up the crops from the content? I re-dropped content this morning but the image tiles still look fuzzy.

**Comment by cguardia** [comment]
The green color is solid, it's the image that's changed to 0.1 opacity. Should I just not display the image on mouseover?

**Comment by alecpm** [comment]
You'll need to make sure the scale is set correctly on the tile in the Layout view, and then re-drop the content to get the correct scale added.

**Comment by skleinfeldt** [comment]
Ah sorry for the bum description @cguardia , yes just don't display the image on mouseover.

Thanks @alecpm for the reminder about making sure the scale is set correctly, that did the trick.

**Comment by cguardia** [comment]
Image should now be hidden on mouseover.

**Comment by skleinfeldt** [comment]
Great!
