### ISSUE TITLE
Styling on contact form

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#75]
- The required button is rather hilarious.
- Make the form fields go full body width - or is that a setting I need to make somewhere?
- Spacing around horizontal line - or eliminate.
- Align Submit button with text.

**Comment by alecpm** [comment]
This should be fixed.

**Comment by skleinfeldt** [comment]
Excellent!

**Comment by skleinfeldt** [comment]
FYI, inputs are different widths on FF and Safari. Not sure which I like best. No need for a fix.
