### ISSUE TITLE
Exported cover layouts disappear 

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#76]
The registry step of our policy (Cris thinks) replaces the list of layouts. It should be set to only add the saved values, rather than overwriting.

**Comment by cewing** [comment]
this has been fixed.  Future installations and upgrades should no longer stomp on saved layouts.

**Comment by skleinfeldt** [comment]
Thank you so much. Haven't had a chance to test yet but I will and will reopen if I find any problems.
