### ISSUE TITLE
Need Team Member listing view

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#8]
This is a custom Folder listing view. Lay it out like this for now, don't sweat the styling.

    +-----------+
    | Image     |  Sally Kleinfeldt
    |           |  Highlight blah blah blah
    |           | 
    |           |
    +-----------+

I wrote this back in April and not sure if relevant: Question whether this will work better if we replace the image field on the content type with lead image behavior.

**Comment by cguardia** [comment]
This is on the beta site now. I created a team members folder and applied this as default view.

**Comment by skleinfeldt** [comment]
Looks good, will open a new ticket when we make styling adjustments. Thanks!
