### ISSUE TITLE
Changes to project page

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#82]
- Increase horizontal space between "Download Case Study" and "View website". Make these bold, all caps and use the lighter blue color with a rollover to the darker blue (unlike all other headings and links) 
- Put a simple black border around the screenshot (a couple pixels?)
- For the quote, indent the text, use the normal font size but in the regular weight instead of the light, and put a quotation mark image in front of it. The person quoted should also be regular weight, and italicized (as currently).

Here is a mockup (although I don't think the Title and Services links are the darker blue, that's from a screen grab).

![project-quote-and-font-treatment-2](https://cloud.githubusercontent.com/assets/1198463/10073547/bde86edc-6297-11e5-8803-3cbfd54a3b8c.png)

**Comment by skleinfeldt** [comment]
Also now that #54 is done, please remove the heading "Similar Projects" that is at the bottom of the view.

**Comment by alecpm** [comment]
When you say a border on the picture, do you want padding between the border and picture (like a photo matting) or just a border directly attached to the image border?

**Comment by skleinfeldt** [comment]
The latter (not photo matting) - at least that is what I'm seeing on Leah's comp, so let's try that.

**Comment by skleinfeldt** [comment]
Just got this from Leah: outline of screenshots=.25 px

**Comment by alecpm** [comment]
A quarter pixel, really?

**Comment by alecpm** [comment]
These changes are done.  I made it a 1px border, since an 0.25px doesn't appear at all here.

**Comment by skleinfeldt** [comment]
Be-yoo-tiful. Agree about the border, she must have been giving us something other than pixel scale.
