### ISSUE TITLE
Slider styling

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#83]
See new design, v14.

- Black band under slider title
- B&W sax image under the slider 
- Large white arrows/angle brackets as shown
- Never show a partial image
- Slide 2 at a time instead of 1
- NO rollover behavior on images - don't show titles, don't darken, don't do anything

**Comment by alecpm** [comment]
This is done.  I hope the angle brackets are big enough.

**Comment by skleinfeldt** [comment]
This is awesome! Couple things:

- Could the scroll be more smooth?
- Could the BG image be lower res? I can watch it paint line by line
- Since you liked it better w/o the black band under the title, remove that so Leah and I can see what it looks like

**Comment by alecpm** [comment]
The black band is gone now:

http://beta.jazkarta.com/about/team/alec-mitchell

I can try a lower res version of that image, it is indeed slow to load the first time.

Regarding the scroll, I'll see what I can do, but it's tricky.  The JS tool we're using only does one item at a time (to do more you need to wrap the items in another container, which we can't really do if we want a generic solution), so to make it do two I added a handler that does a second scroll after the first one when the buttons are clicked.  I may be able to disable the original scroll behavior and have the custom behavior do a two item scroll.

**Comment by alecpm** [comment]
OK Image resolution is lower and scrolling is smoother.

**Comment by skleinfeldt** [comment]
Excellent, much better (res and scrolling). Also great that the arrow is greyed out when you reach the end.

I like it w/o the black band, we'll see if Leah has strong feelings.

One slight problem: on FF the arrows/angle brackets are much bigger and heavier, not so pretty. Maybe related to #87?

**Comment by alecpm** [comment]
Looks like using relative font sizes for those brackets is not a good choice.  I've set a fixed size for those, should be deployed momentarily.

**Comment by skleinfeldt** [comment]
Much better (although still not as pretty on FF).
