### ISSUE TITLE
Adjust headings

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#84]
Adjust sizes and colors of H1, H2, and H3 headings, per v14 of the design

**Comment by alecpm** [comment]
Should be done

**Comment by skleinfeldt** [comment]
Huzzah!

**Comment by skleinfeldt** [comment]
Belatedly got this from Leah, so adding here:

Heading specs: 

- H1 - 40/black
- H2 - 32/semibold
- H3 - 24/semibold

The darkest blue for H1 and H2, and black for H3.

Body - 21/light, line spacing 29.

**Comment by alecpm** [comment]
Hm, these seem much larger than what I'm seeing relative to the v14 mockup of the headings, must just be a difference in the font metrics on the site vs the comps.

I'm using:

* H1 - 36px/Bold(800)
* H2 - 25px/Semibold(600)
* H3 - 20px/Semibold(600)
* H4 - 18px/Semibold(600)

Body - 18px/light(300) line height 1.42857143 (perhaps we should make this 1.38 to match the ratio above)

**Comment by skleinfeldt** [comment]
Well it looks good to me so let's leave it as is. Or make the change you indicate if that seems good.

**Comment by alecpm** [comment]
The change was already there by the time I had a non-failed deploy.  It makes no difference to my eyes though.
