### ISSUE TITLE
"Vertically Centered Text Tile" selection borks Layout view

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#86]
If you select CSS style "Vertically Centered Text Tile" on a Rich Text tile, then go to Compose and add some text, then go back to Layout, the Rich Text box on the grid has grown such that you can no longer "reach" the gear. Observed on FF at http://beta.jazkarta.com/services/plone-websites/plone-websites/layoutedit

Low priority since you can always delete and re-add. Still, something is wrong here.

**Comment by alecpm** [comment]
This style option seems to be gone in current cover versions.
