### ISSUE TITLE
Tile fonts bigger on FF

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#87]
Comparing http://beta.jazkarta.com/services/plone-websites/plone-websites on Safari and FF, the font size in the basic tiles is noticeably larger on FF - so much so that text that fits on Safari doesn't fit on FF. It would be great if this could be fixed so I don't have to remember to check cover layouts on both browsers...

**Comment by skleinfeldt** [comment]
I just realized that the whole header is bigger on FF - the blue and the green and the banner parts individuallty are bigger. Also the homepage banner is much bigger too. What's up with that??

**Comment by alecpm** [comment]
I'm not seeing this locally.  I wonder if there's a font loading issue any errors in your browser console?  Perhaps you have the zoom level set to something non-standard in FF (try View -> Zoom -> Reset or Command-0)

**Comment by skleinfeldt** [comment]
Zoom Reset did nothing. Web Developer console says "window.controllers is deprecated. Do not use it for UA detection." when I reload copy_of_front-page. Is there something else I should check? (BTW I'm seeing this as anonymous.)

**Comment by alecpm** [comment]
Is anyone else seeing this?  @davisagli @cewing @cguardia?

**Comment by davisagli** [comment]
Looks the same for me in all 3 browsers.

**Comment by skleinfeldt** [comment]
That's very odd. FWIW I am still seeing this.

Safari Version 8.0.8 (10600.8.9)
FF 40.0.3 (it'll update when I restart, will check again after that)
OSX 10.10.5 (14F27)

Low priority

**Comment by skleinfeldt** [comment]
Whatever this issue was, it is gone now!
