### ISSUE TITLE
Use portlets instead of lead images for inner page banners

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#9]
So they can be inherited and we don't need to enter a lead image for every page.

**Comment by davisagli** [comment]
(or make our custom leadimage view look for images from parents)

**Comment by skleinfeldt** [comment]
As explained on #13, inner page design may change, so hold on this for now.

**Comment by skleinfeldt** [comment]
Closing wontfix. Finding good lead images for every page (even if inherited) is too problematic, need a different design solution that does not require this.
