### ISSUE TITLE
Lost thumb image sizes for relatedslider

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#91]
Did I do something to change this? Relatedslider no longer seems to be using the thumb crop. For example http://beta.jazkarta.com/services/cloud-hosting/opsworks-deployments

**Comment by alecpm** [comment]
I'm not sure what happened there, but resaving the crops (which were still set in the interface) fixed the issue.  It could have been an issue with the varnish cache (which gets purged on crop re-save) or with something internal causing the thumbs to be generated uncropped despite the cropping info being preserved.  If this happens again, let me know and I can look into it further.

**Comment by skleinfeldt** [comment]
@alecpm I just tried to resave the crops for http://beta.jazkarta.com/projects/my-dante multiple times. Each time it seemed to keep the crop information in the area where you work on the crops, but it isn't showing in the the area where it shows each size, and it isn't showing here http://beta.jazkarta.com/services/cloud-hosting/heroku-deployments. It also complains that I'm going to loose my changes after I finish with one crop and move on to the next. It didn't used to to do that, after saving a crop it wouldn't complain when you selected another size.

I'm going to wait to resave all my crops until after you are more sure this is working...

**Comment by alecpm** [comment]
It showed up after I shift-reloaded the crops page.  That indicates it's a browser caching issue.  Not sure what we can do about that, but I'll give it some thought.  Perhaps the cropping tool should append a time based query string to the cropped images to ensure caching isn't in play?

**Comment by skleinfeldt** [comment]
It may be a browser caching issue on the Cropping page, but the fact that it is not using the crops is not a browser caching issue. I just created a new project for the MIT work http://beta.jazkarta.com/projects/custom-courses-for-edx and cropped the image, but the cropped thumb version does not appear on a related project's slider: http://beta.jazkarta.com/projects/molecule-editor-for-open-edx

**Comment by skleinfeldt** [comment]
There is another irritating but not show stopping behavior the cropping tool is showing, which I think was not the case when I started. Go to any image, choose the cropping tool, select one of the sizes to crop, scroll down to the working area, and click in the working area. The page jumps up, putting the working area out of reach until you scroll back.

Not a serious problem but maybe it is a clue to what is going on.

**Comment by skleinfeldt** [comment]
More data: I started here: http://beta.jazkarta.com/services/open-edx-consulting/edx-components which was not showing the correct crop. I clicked on the project and used the cropping tool and resaved my (still in the tool) crops. Then I shift-reloaded the cropping page and yes, that made the crops show on that page. Then I went back to the page I started from, and the correct crop is now showing.

Is this the process I need to follow to get all the crops to show? Go to each item, resave the crops, and then shift-reload. Seems odd, but whatever works. 

Please let me know, I only want to do this once...

**Comment by alecpm** [comment]
Yes, that is what worked for me.  So far, everything I've seen indicates that this is a proxy/browser caching issue (should be easy to track down).  I'll need to double check that the cache purge is happening as expected, but probably also add a cache-busting query string on the crop interface.

**Comment by skleinfeldt** [comment]
I fixed all the project images, hoping this is now stable.

The cropping tool is incredibly useful, but the UI is really irritating with all the prompting about losing changes and jumping around and having to shift reload. Not ready to go into Plone core yet.

Close this when you've done whatever else you think necessary.

**Comment by skleinfeldt** [comment]
@alecpm the thumb crops that I made for the project images are working (I think) for the relatedsliders. But @cewing is now using them for the Isotope view, and thumbs that look right on relatedslider don't all look right there. See for example the MassChallenge thumb here
http://beta.jazkarta.com/projects/get-lost-montana
versus here
http://beta.jazkarta.com/projects/projects/

When I first noticed the problem looking at the isotope page I thought it was just the KCRW image that had lost its crop (because it was obviously wrong and it through off the grid.) So I went to the cropping page for that, the crops did not show properly on that page, so I fixed them using the save plus shift-reload routine. Then when I went back to the projects page I saw that MassChallenge, Innocence Project, Get Lost, and probably others looked wrong as well. Then I discovered that they look right on the related slider.

And oh shit - now I see that the one I just "fixed", KCRW, looks wrong on the relatedslider! 
http://beta.jazkarta.com/projects/collective-salesforce-fundraising

Please help!

**Comment by alecpm** [comment]
The Projects listing is throwing an error for me, but IIRC that page isn't using the same image scale as the related slider.  I don't reacall which one it's using, but I can check.  The KCRW thumb on the related slider looks fine to me, I think there's a bit of an optical illusion because the dark grey header in the image blends with the B&W saxophone background.

**Comment by skleinfeldt** [comment]
Yes I'm seeing some odd behavior on the isotope view, I'll open a new ticket for that. Haven't gotten an actual error though.

Try shift-reloading http://beta.jazkarta.com/projects/collective-salesforce-fundraising - when I just now went back to it, it looked fine but when I shift-reloaded it lost the crop.

**Comment by skleinfeldt** [comment]
Just went to MyDante project page on my iPhone and the Go Orchids and MassChallenge thumbs are wrong. Get Lost Montana is right and Go Botany I can't tell because of the responsive issue in the last comment on #99.

**Comment by skleinfeldt** [comment]
I just went through and carefully resaved all Project image crops. (Tedious, exacerbated by 12 clicks/project given all the "you might lose changes" warnings.)

I'm going through the site to verify all is well, and what the heck! The Mountaineers crop shows correctly here http://beta.jazkarta.com/projects but not here http://beta.jazkarta.com/services/plone-websites/plone-hosting if I am logged in. I can shift-reload all I want. If I am not logged in it looks correct.

Another breadcrumb. 

The cropping add-on is incredibly useful, but it really needs work before it's ready for Plone core (where I think it should be. All the confirmation clicks and losing the crops are a terrible problem.

**Comment by cguardia** [comment]
It's a caching thing. I opened the image in a new tab and reloaded that, then it was fixed for me.

**Comment by alecpm** [comment]
We are now using the 2.x line of p.a.imagecropping, which has totally re-architected the scale storage etc. This may once again break all the crops (though I think it shouldn't). I'm closing this, because I think we've fixed it completely modulo some caching issues.
