### ISSUE TITLE
Left justify the lower "View Website" link on project view

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#92]
Instead of right justify like it is now. Minor view tweak.

**Comment by skleinfeldt** [comment]
@cguardia ping?

**Comment by cguardia** [comment]
Sorry, lost track of this one. Fixed.

**Comment by skleinfeldt** [comment]
@cguardia can you deploy this? I'm not seeing it.

**Comment by cguardia** [comment]
I see it on the left. Caching?

**Comment by skleinfeldt** [comment]
I guess so - even though I had shift-reloaded. Looks right now though!
