### ISSUE TITLE
Browser testing

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#94]
Sally has been testing on FF and Safari on a Macbook Pro 10.10.5, and Safari on iPhone 6 and 1 year old iPad. We need to sanity check on IE and anything else that seems important. By emulator or whatever.

Do this after @alecpm says the theme is ready.

**Comment by skleinfeldt** [comment]
@cguardia we're pretty much ready to go theme-wise. It would be great if you could sanity check the site on IE or an IE emulator.

**Comment by cguardia** [comment]
I checked on Android (Kindle Fire) and IE 10 and 11. Looks good.

**Comment by skleinfeldt** [comment]
Taking your word for it!
