### ISSUE TITLE
iPad landing pages should display 3 tiles across

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#97]
I think I remember that it was not easy or possible to reduce the tile layout from 3 across to 2 across to 1 across - it has to go from 3 to 1. That's fine, but the breakpoint for that is set so we get 1 across on our iPad which looks pretty silly. It seems like it should be readable/usable to continue at 3 across until you are below all iPad/tablet screen sizes?

**Comment by alecpm** [comment]
Yeah, that's the intent it's just that the breakpoints and viewport are apparently not quite right for the devices in question.  I was trying to avoid using JS to set the viewport (we do that for KCRW though), but it may be unavoidable, given the variations in mobile device widths these days.

**Comment by skleinfeldt** [comment]
Yay, 3 across looks awesome on iPad!!! However there is whitespace to right of header and footer on iPad and iPhone 6 - can that be fixed?

**Comment by skleinfeldt** [comment]
Moved whitespace issue to #100
