### ISSUE TITLE
Homepage banner text

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#98]
On iPad the text overlaid on the homepage banner image falls off the bottom. Would it be better to just have Leah give us an image with the text incorporated? She wants to do that because she wants to make the text look prettier. I have been resisting because I want control over the text. But I'd rather lose control over the text than have to worry about responsive issues with it. What do you think?

**Comment by davisagli** [comment]
If we put the text in the image, it still has responsive issues because it'll become unreadable at narrow widths. So we should probably just fix the issues we have.

**Comment by alecpm** [comment]
It shouldn't be hard to find a placement that works at the different breakpoints, it's just that we have yet to try it.  I'll be testing the site at the standard widths this week and tweaking styling at the various breakpoints a bit more.

**Comment by skleinfeldt** [comment]
So while you are tweaking, can you increase the distance between the lines of the overlay text? The lines being so close is really bugging Leah.

**Comment by davisagli** [comment]
Actually I guess it would be useful for Leah to give a mockup of how it should ideally look, and then we could see how close we can get to that with css.

**Comment by alecpm** [comment]
Indeed, otherwise it's just trial and error.  I understand if you don't want to bother Leah too much though.

**Comment by skleinfeldt** [comment]
I asked - however I'm pretty sure she won't have time until the weekend...

**Comment by skleinfeldt** [comment]
@alecpm you now have Leah's design for this.

**Comment by alecpm** [comment]
I think I implemented this already.

**Comment by skleinfeldt** [comment]
Ah OK - placement of text is perfect now, the lines are still close together (that's what the comp was for) but if that's hard to match, oh well.

**Comment by alecpm** [comment]
Spacing should be better now.

**Comment by skleinfeldt** [comment]
Perfect!
