### ISSUE TITLE
Slider responsive behavior

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#99]
The slider goes from 3 across at a larger image size, to 2 across at a smaller image size (which gives an excess of space around the slider on the iPad), and it never goes to 1 across for phones (which forces the page to be much wider than the phone). Would it be possible to have these breakpoints:

    3 across at larger image size (desktop)
    3 across at smaller image size (iPad)
    2 across at smaller image size (smaller desktop windows, smaller iPads)
    1 across at smaller image size (phones)

**Comment by alecpm** [comment]
One across is a little tricky since we scroll two at a time.  Could we just make the two images a bit smaller?  Changing the scrolling behavior responsively could work, but it might be tricky to get right.

**Comment by skleinfeldt** [comment]
Good point, sure make the 2 smaller.

**Comment by skleinfeldt** [comment]
This now looks great on iPads, and better on iPhone 6. There is a bit of an issue on iPhone: since it scrolls 2 at a time, and when 2 are shown only a tiny bit of the 2nd image is shown, you never really get to see the 2nd, 4th, 5th, etc. images.

**Comment by skleinfeldt** [comment]
I guess ideally it should scroll by 1 instead of 2 on phone viewports. Is that possible?

**Comment by alecpm** [comment]
I think it's better to shrink the images in the scroller to ensure 2 fit at all display resolutions, rather than try to match the number of scrolled items to the size of the scroller.

**Comment by skleinfeldt** [comment]
Try that, I'm worried the shrunk images on phones will be illegibly small.

**Comment by alecpm** [comment]
I've made some more tweaks to the slider responsiveness.  Seems to look decent for mobile and ipad now.

**Comment by skleinfeldt** [comment]
Looks fantastic!
